<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Statystyki centrograficzne – Statystyka przestrzenna</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07_punkty_intensywnosc.html" rel="next">
<link href="./05_punkty_teoria.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c852b7e71cc1c09f55f367b2512aabbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Brak wyników",
    "search-matching-documents-text": "dopasowane dokumenty",
    "search-copy-link-title": "Kopiuj link do wyszukiwania",
    "search-hide-matches-text": "Ukryj dodatkowe dopasowania",
    "search-more-match-text": "więcej dopasowań w tym dokumencie",
    "search-more-matches-text": "więcej dopasowań w tym dokumencie",
    "search-clear-button-title": "Wyczyść",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Anuluj",
    "search-submit-button-title": "Zatwierdź",
    "search-label": "Szukaj"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_punkty_teoria.html">DANE PUNKTOWE</a></li><li class="breadcrumb-item"><a href="./06_punkty_centrograficzne.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Szukaj" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statystyka przestrzenna</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Szukaj"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O skrypcie</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_wstep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WSTĘP</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_dane_przestrzenne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Dane przestrzenne w R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_eksploracja_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EKSPLORACYJNA ANALIZA DANYCH</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_eksploracja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Eksploracyjna analiza danych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05_punkty_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE PUNKTOWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_punkty_centrograficzne.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_punkty_intensywnosc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_punkty_odleglosc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Metody oparte na odległości</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./09_obszarowe_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE OBSZAROWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_obszarowe_sasiedztwo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Określanie sąsiedztwa danych obszarowych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_obszarowe_autokorelacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Miary autokorelacji danych obszarowych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./12_pola_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE POWIERZCHNIOWE CIĄGŁE PRZESTRZENNIE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_pola_interpolacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Metody interpolacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_pola_semiwariogram.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_pola_estymacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Geostatystyczne metody estymacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_pola_ocena.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Ocena jakości estymacji</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">ZADANIA I PROJEKTY</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_zadania_samodzielne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Zadania samodzielne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_projekt1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Projekt 1: przestępczość a zmienne społeczno-ekonomiczne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_projekt2_geostatystyka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Projekt 2: Geostatystyka</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Załączniki</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A_pakiety.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Pakiety</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B_funkcje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Funkcje</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C_operacje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Operacje na danych przestrzennych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D_slownik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Słownik pojęć</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Spis treści</h2>
   
  <ul>
  <li><a href="#wprowadzenie" id="toc-wprowadzenie" class="nav-link active" data-scroll-target="#wprowadzenie"><span class="header-section-number">3.1</span> Wprowadzenie</a></li>
  <li><a href="#statystyki-centrograficzne-w-r" id="toc-statystyki-centrograficzne-w-r" class="nav-link" data-scroll-target="#statystyki-centrograficzne-w-r"><span class="header-section-number">3.2</span> Statystyki centrograficzne w R</a></li>
  <li><a href="#przykład-1-przestępczość-w-poznaniu" id="toc-przykład-1-przestępczość-w-poznaniu" class="nav-link" data-scroll-target="#przykład-1-przestępczość-w-poznaniu"><span class="header-section-number">3.3</span> Przykład 1: Przestępczość w Poznaniu</a>
  <ul class="collapse">
  <li><a href="#dane" id="toc-dane" class="nav-link" data-scroll-target="#dane">Dane</a></li>
  <li><a href="#krok-1-średnia-centralna" id="toc-krok-1-średnia-centralna" class="nav-link" data-scroll-target="#krok-1-średnia-centralna">Krok 1: średnia centralna</a></li>
  <li><a href="#krok-2-mediana-centralna" id="toc-krok-2-mediana-centralna" class="nav-link" data-scroll-target="#krok-2-mediana-centralna">Krok 2: mediana centralna</a></li>
  <li><a href="#krok-3-odległość-standardowa" id="toc-krok-3-odległość-standardowa" class="nav-link" data-scroll-target="#krok-3-odległość-standardowa">Krok 3: odległość standardowa</a></li>
  <li><a href="#krok-4-elipsa-odchylenia-standardowego" id="toc-krok-4-elipsa-odchylenia-standardowego" class="nav-link" data-scroll-target="#krok-4-elipsa-odchylenia-standardowego">Krok 4: elipsa odchylenia standardowego</a></li>
  <li><a href="#krok-5-wizualizacja" id="toc-krok-5-wizualizacja" class="nav-link" data-scroll-target="#krok-5-wizualizacja">Krok 5: wizualizacja</a></li>
  <li><a href="#interpretacja-wyniku" id="toc-interpretacja-wyniku" class="nav-link" data-scroll-target="#interpretacja-wyniku">Interpretacja wyniku</a></li>
  <li><a href="#skąd-się-biorą-te-liczby" id="toc-skąd-się-biorą-te-liczby" class="nav-link" data-scroll-target="#skąd-się-biorą-te-liczby">Skąd się biorą te liczby</a></li>
  </ul></li>
  <li><a href="#przykład-2-szkoły-podstawowe-w-poznaniu" id="toc-przykład-2-szkoły-podstawowe-w-poznaniu" class="nav-link" data-scroll-target="#przykład-2-szkoły-podstawowe-w-poznaniu"><span class="header-section-number">3.4</span> Przykład 2: Szkoły podstawowe w Poznaniu</a>
  <ul class="collapse">
  <li><a href="#przygotowanie-danych" id="toc-przygotowanie-danych" class="nav-link" data-scroll-target="#przygotowanie-danych">Przygotowanie danych</a></li>
  <li><a href="#dane-1" id="toc-dane-1" class="nav-link" data-scroll-target="#dane-1">Dane</a></li>
  <li><a href="#krok-1-obliczenie-statystyk-centrograficznych" id="toc-krok-1-obliczenie-statystyk-centrograficznych" class="nav-link" data-scroll-target="#krok-1-obliczenie-statystyk-centrograficznych">Krok 1: obliczenie statystyk centrograficznych</a></li>
  <li><a href="#krok-2-wizualizacja" id="toc-krok-2-wizualizacja" class="nav-link" data-scroll-target="#krok-2-wizualizacja">Krok 2: wizualizacja</a></li>
  <li><a href="#krok-3-porównanie-z-przestępstwami" id="toc-krok-3-porównanie-z-przestępstwami" class="nav-link" data-scroll-target="#krok-3-porównanie-z-przestępstwami">Krok 3: porównanie z przestępstwami</a></li>
  <li><a href="#sprawdź-swoją-interpretację" id="toc-sprawdź-swoją-interpretację" class="nav-link" data-scroll-target="#sprawdź-swoją-interpretację">Sprawdź swoją interpretację</a></li>
  </ul></li>
  <li><a href="#pytania-kontrolne" id="toc-pytania-kontrolne" class="nav-link" data-scroll-target="#pytania-kontrolne"><span class="header-section-number">3.5</span> Pytania kontrolne</a></li>
  <li><a href="#podsumowanie" id="toc-podsumowanie" class="nav-link" data-scroll-target="#podsumowanie"><span class="header-section-number">3.6</span> Podsumowanie</a></li>
  <li><a href="#pytania-dla-dwóch-kolejnych-rozdziałów" id="toc-pytania-dla-dwóch-kolejnych-rozdziałów" class="nav-link" data-scroll-target="#pytania-dla-dwóch-kolejnych-rozdziałów"><span class="header-section-number">3.7</span> Pytania dla dwóch kolejnych rozdziałów</a></li>
  <li><a href="#pełny-kod-analizy" id="toc-pełny-kod-analizy" class="nav-link" data-scroll-target="#pełny-kod-analizy"><span class="header-section-number">3.8</span> Pełny kod analizy</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_punkty_teoria.html">DANE PUNKTOWE</a></li><li class="breadcrumb-item"><a href="./06_punkty_centrograficzne.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-punkty-centrograficzne" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Czego się nauczysz
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Po tym rozdziale potrafisz wykonać w R:</strong></p>
<ul>
<li>obliczyć średnią centralną i medianę centralną zbioru punktów,</li>
<li>obliczyć odległość standardową i przedstawić ją na mapie jako okrąg,</li>
<li>obliczyć elipsę odchylenia standardowego i przedstawić ją na mapie,</li>
<li>złożyć wszystkie statystyki centrograficzne na jednej mapie wraz z punktami i granicą obszaru analizy.</li>
</ul>
<p><strong>Rozumiesz i umiesz zinterpretować:</strong></p>
<ul>
<li>co opisuje każda z czterech statystyk i czego <strong>nie</strong> opisuje,</li>
<li>odległość standardową jako miarę rozproszenia — przez porównanie z wartością dla innego zbioru w tym samym obszarze,</li>
<li>dlaczego kierunek elipsy w dużej mierze odzwierciedla kształt obszaru badań,</li>
<li>dlaczego elipsa wyglądająca na bardziej wydłużoną może nieść mniej informacji,</li>
<li>relację między średnią a medianą centralną jako sprawdzenie wpływu lokalizacji skrajnych.</li>
</ul>
<p><strong>Teoria:</strong> <a href="./05_punkty_teoria.html#najwazniejsze-punkty">Najważniejsze informacje</a>. <strong>Operacje techniczne:</strong> <a href="C_operacje.html" class="quarto-xref"><span>Załącznik C</span></a>. <strong>Funkcje:</strong> <a href="B_funkcje.html" class="quarto-xref"><span>Załącznik B</span></a>.</p>
</div>
</div>
<section id="wprowadzenie" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="wprowadzenie"><span class="header-section-number">3.1</span> Wprowadzenie</h2>
<p>Statystyki centrograficzne są przestrzennym odpowiednikiem statystyk opisowych: tak jak średnia i odchylenie standardowe podsumowują zbiór liczb dwiema wartościami, tak statystyki centrograficzne podsumowują zbiór punktów ich <strong>położeniem środkowym</strong>, <strong>rozproszeniem</strong> oraz <strong>kierunkiem rozproszenia</strong>. Są najprostszą formą opisu rozkładu przestrzennego danych punktowych i pierwszym krokiem analizy.</p>
<p>Statystyki centrograficzne opisują zbiór punktów jako całość. Pytanie o <strong>typ rozkładu</strong> — losowy, skupiony czy regularny — wymaga zbadania relacji między poszczególnymi punktami i należy do metod opartych na intensywności (<a href="07_punkty_intensywnosc.html" class="quarto-xref"><span>Rozdział 4</span></a>) oraz na odległości (<a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>). Statystyki centrograficzne są natomiast niezastąpione przy <strong>porównywaniu zbiorów</strong> — dwóch typów obiektów w tym samym obszarze albo tego samego zjawiska w dwóch okresach. Tak też są używane w tym rozdziale: Przykład 1 opisuje rozkład przestępstw, Przykład 2 rozkład szkół, a wnioski płyną z porównania obu.</p>
<p>Definicje statystyk centrograficznych zawiera <a href="./05_punkty_teoria.html">rozdział teoretyczny części</a>. W tym rozdziale przy każdym kroku podane jest, co dana statystyka mówi o danych.</p>
</section>
<section id="statystyki-centrograficzne-w-r" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="statystyki-centrograficzne-w-r"><span class="header-section-number">3.2</span> Statystyki centrograficzne w R</h2>
<p>Statystyki centrograficzne oblicza się funkcjami z pakietu <code>sfdep</code>, działającymi bezpośrednio na obiektach klasy <code>sf</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Funkcja</th>
<th>Co zwraca</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>center_mean()</code></td>
<td>średnia centralna — obiekt <code>sfc_POINT</code></td>
</tr>
<tr class="even">
<td><code>center_median()</code></td>
<td>mediana centralna — obiekt <code>sfc_POINT</code></td>
</tr>
<tr class="odd">
<td><code>std_distance()</code></td>
<td>odległość standardowa — <strong>liczba</strong> w jednostkach układu współrzędnych</td>
</tr>
<tr class="even">
<td><code>std_dev_ellipse()</code></td>
<td>parametry elipsy: <code>sx</code>, <code>sy</code>, <code>theta</code> oraz geometria średniej centralnej</td>
</tr>
<tr class="odd">
<td><code>st_ellipse()</code></td>
<td>zamienia parametry elipsy na obiekt liniowy, który można narysować</td>
</tr>
</tbody>
</table>
<p>Dwie z nich zwracają liczby, nie geometrię, więc żeby umieścić je na mapie, trzeba je najpierw zamienić na obiekt przestrzenny: odległość standardową funkcją <code>st_buffer()</code>, parametry elipsy funkcją <code>st_ellipse()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sfdep)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="przykład-1-przestępczość-w-poznaniu" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="przykład-1-przestępczość-w-poznaniu"><span class="header-section-number">3.3</span> Przykład 1: Przestępczość w Poznaniu</h2>
<section id="dane" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dane">Dane</h3>
<ul>
<li><code>data/przestepstwa_2019.gpkg</code> — lokalizacje przestępstw w Poznaniu w 2019 roku; warstwa punktowa bez atrybutów, zawiera wyłącznie kolumnę geometrii,</li>
<li><code>data/out_poznan_szkoly.gpkg</code>, warstwa <code>granica</code> — granica miasta Poznania, pozyskana z Bazy Danych Obiektów Topograficznych. Sposób jej przygotowania pokazuje Przykład 2; <strong>oba przykłady używają tej samej granicy</strong>, więc ich wyniki można porównywać bezpośrednio.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>p2019 <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/przestepstwa_2019.gpkg"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"granica"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(p2019)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1661</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_punkty_centrograficzne_files/figure-html/p1-dane-b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="krok-1-średnia-centralna" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-1-średnia-centralna">Krok 1: średnia centralna</h3>
<p><strong>Średnia centralna</strong> to punkt o współrzędnych będących średnimi arytmetycznymi współrzędnych wszystkich punktów zbioru. Odpowiada średniej arytmetycznej w statystyce klasycznej i wskazuje położenie środkowe całego zbioru.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mc <span class="ot">=</span> <span class="fu">center_mean</span>(p2019)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mc</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 1 feature 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 358716.4 ymin: 506363.5 xmax: 358716.4 ymax: 506363.5
Projected CRS: ETRF2000-PL / CS92</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT (358716.4 506363.5)</code></pre>
</div>
</div>
</section>
<section id="krok-2-mediana-centralna" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-2-mediana-centralna">Krok 2: mediana centralna</h3>
<p><strong>Mediana centralna</strong> to punkt o współrzędnych będących medianami współrzędnych, wyznaczanymi osobno dla każdej osi. Tak jak mediana w statystyce klasycznej, jest odporna na wartości skrajne.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>md <span class="ot">=</span> <span class="fu">center_median</span>(p2019)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>md</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 1 feature 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 358816.1 ymin: 506128.6 xmax: 358816.1 ymax: 506128.6
Projected CRS: ETRF2000-PL / CS92</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT (358816.1 506128.6)</code></pre>
</div>
</div>
<p>Porównanie położenia obu środków jest prostym sprawdzeniem, czy średnia centralna nie jest przesunięta przez nietypowe lokalizacje. Odległość między nimi liczymy funkcją <code>st_distance()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(mc, md)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Units: [m]
         [,1]
[1,] 255.1896</code></pre>
</div>
</div>
</section>
<section id="krok-3-odległość-standardowa" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-3-odległość-standardowa">Krok 3: odległość standardowa</h3>
<p><strong>Odległość standardowa</strong> to średnia kwadratowa odległości punktów od średniej centralnej:</p>
<p><span class="math display">\[d = \sqrt{\frac{\sum_{i=1}^{n} \left[(x_i - \overline{x_c})^2 + (y_i - \overline{y_c})^2\right]}{n}}\]</span></p>
<p>Jest odpowiednikiem odchylenia standardowego: opisuje, jak daleko od środka rozproszone są punkty. Wyrażona jest w jednostkach układu współrzędnych — tutaj w metrach, bo dane są w PUWG 1992 (<code>EPSG:2180</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sd_odl <span class="ot">=</span> <span class="fu">std_distance</span>(p2019)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sd_odl</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3886.935</code></pre>
</div>
</div>
<p>Funkcja zwraca liczbę, nie geometrię. Aby przedstawić odległość standardową na mapie jako okrąg o środku w średniej centralnej, tworzymy strefę buforową o promieniu równym tej liczbie.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sd_okrag <span class="ot">=</span> <span class="fu">st_buffer</span>(mc, sd_odl)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="krok-4-elipsa-odchylenia-standardowego" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-4-elipsa-odchylenia-standardowego">Krok 4: elipsa odchylenia standardowego</h3>
<p><strong>Elipsa odchylenia standardowego</strong> rozdziela rozproszenie na dwa prostopadłe kierunki. Opisują ją trzy parametry: długości półosi <code>sx</code> i <code>sy</code> oraz kąt obrotu <code>theta</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>elipsa_par <span class="ot">=</span> <span class="fu">std_dev_ellipse</span>(p2019)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>elipsa_par</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 358716.4 ymin: 506363.5 xmax: 358716.4 ymax: 506363.5
Projected CRS: ETRF2000-PL / CS92
        sx       sy    theta                  geometry
1 3731.287 4041.095 136.7049 POINT (358716.4 506363.5)</code></pre>
</div>
</div>
<p>Kąt <code>theta</code> jest <strong>azymutem dłuższej osi</strong> — mierzony jest zgodnie z ruchem wskazówek zegara od kierunku północnego, w zakresie od 0 do 180°. Półoś <code>sy</code> odpowiada temu kierunkowi, a <code>sx</code> jest do niego prostopadła.</p>
<p>Stosunek dłuższej półosi do krótszej mówi, jak silnie rozkład jest wydłużony. Wartość bliska 1 oznacza rozproszenie jednakowe we wszystkich kierunkach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>elipsa_par<span class="sc">$</span>sy <span class="sc">/</span> elipsa_par<span class="sc">$</span>sx</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.08303</code></pre>
</div>
</div>
<p>Funkcja <code>std_dev_ellipse()</code> zwraca parametry, nie geometrię — obiekt do narysowania tworzy funkcja <code>st_ellipse()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>elipsa <span class="ot">=</span> <span class="fu">st_ellipse</span>(elipsa_par, <span class="at">sx =</span> elipsa_par<span class="sc">$</span>sx, <span class="at">sy =</span> elipsa_par<span class="sc">$</span>sy)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="krok-5-wizualizacja" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-5-wizualizacja">Krok 5: wizualizacja</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sd_okrag) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(elipsa) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(mc) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(md) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06_punkty_centrograficzne_files/figure-html/p1-krok5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Statystyki centrograficzne dla przestępstw w Poznaniu w 2019 roku: średnia centralna (czerwony punkt), mediana centralna (niebieski punkt), odległość standardowa (czerwony okrąg), elipsa odchylenia standardowego (zielona linia).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretacja-wyniku" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretacja-wyniku">Interpretacja wyniku</h3>
<p><strong>Położenie środkowe.</strong> Średnia centralna leży w centralnej części miasta. Mediana centralna leży 255 m od niej, co stanowi zaledwie 7% odległości standardowej. Oba środki praktycznie się pokrywają, więc <strong>średnia centralna nie jest zaburzona przez nietypowe lokalizacje</strong> — nie ma pojedynczych przestępstw położonych tak daleko od pozostałych, żeby przeciągnąć środek. Gdyby odległość między środkami była znaczna, oznaczałoby to, że część punktów leży skrajnie i że do opisu położenia lepiej użyć mediany.</p>
<p><strong>Rozproszenie.</strong> Odległość standardowa wynosi 3887 m. Okrąg o tym promieniu, widoczny na mapie, obejmuje centralną część miasta — przeciętne przestępstwo leży niemal 4 km od środka zbioru. Wartość wyrażona jest w metrach, bo dane są w układzie odwzorowanym PUWG 1992 (<code>EPSG:2180</code>); w układzie współrzędnych geograficznych otrzymalibyśmy stopnie, czyli liczbę bezużyteczną.</p>
<p>Sama ta liczba nie mówi jeszcze, czy jest to dużo, czy mało — nabiera znaczenia dopiero w porównaniu, które wykonamy w Przykładzie 2, gdzie te same statystyki policzymy dla szkół w tym samym obszarze.</p>
<p><strong>Kierunek rozproszenia.</strong> Stosunek osi elipsy wynosi 1.08, czyli jest bliski jedności: rozkład jest niemal kolisty. Ma to zasadniczą konsekwencję dla czytania azymutu. Azymut dłuższej osi wynosi wprawdzie 136.7°, co wskazywałoby kierunek NW–SE, ale <strong>dla elipsy niemal kolistej azymut nie wskazuje żadnego rzeczywistego kierunku</strong> — przy osiach niemal równej długości to, która z nich wypadnie dłuższa, decyduje się na poziomie drobnych różnic.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kierunek elipsy a kształt obszaru badań
</div>
</div>
<div class="callout-body-container callout-body">
<p>Przed uznaniem kierunku elipsy za właściwość badanego zjawiska porównaj go wzrokowo z granicą obszaru analizy na mapie. Punkty leżą zawsze wewnątrz jakiegoś obszaru, a jeśli obszar jest wydłużony, to wydłużenie przenosi się na elipsę — niezależnie od tego, jak punkty są w nim rozmieszczone. Granica Poznania jest wydłużona w kierunku NW–SE, czyli dokładnie tym, który wskazuje azymut elipsy przestępstw.</p>
<p>Kierunek elipsy interpretuje się więc tylko wtedy, gdy spełnione są dwa warunki: elipsa jest <strong>wyraźnie wydłużona</strong> (stosunek osi odbiega od jedności) <strong>i</strong> jej kierunek <strong>nie pokrywa się</strong> z kierunkiem obszaru badań.</p>
</div>
</div>
</section>
<section id="skąd-się-biorą-te-liczby" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="skąd-się-biorą-te-liczby">Skąd się biorą te liczby</h3>
<p>Warto raz sprawdzić, że funkcje liczą dokładnie to, co podają wzory. Jeśli kiedyś nie będziesz pewna, co dana funkcja oblicza, najprostszą drogą jest odtworzenie jej na małym przykładzie.</p>
<p>Funkcja <code>st_coordinates()</code> wydobywa współrzędne z obiektu punktowego do macierzy o dwóch kolumnach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">=</span> <span class="fu">st_coordinates</span>(p2019)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(xy)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            X        Y
[1,] 361379.5 503546.3
[2,] 361691.3 503694.6
[3,] 360347.3 506216.0
[4,] 353099.3 504204.1
[5,] 361715.2 503305.9
[6,] 360260.9 510415.0</code></pre>
</div>
</div>
<p>Średnia centralna to po prostu średnie arytmetyczne obu kolumn:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(xy, <span class="dv">2</span>, mean)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       X        Y 
358716.4 506363.5 </code></pre>
</div>
</div>
<p>Odległość standardowa to średnia kwadratowa odległości od tego punktu:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mc_xy <span class="ot">=</span> <span class="fu">apply</span>(xy, <span class="dv">2</span>, mean)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>((xy[, <span class="dv">1</span>] <span class="sc">-</span> mc_xy[<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (xy[, <span class="dv">2</span>] <span class="sc">-</span> mc_xy[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">nrow</span>(xy))</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3886.935</code></pre>
</div>
</div>
<p>Oba wyniki zgadzają się z wartościami zwróconymi przez <code>center_mean()</code> i <code>std_distance()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">as.numeric</span>(mc_xy), <span class="fu">as.numeric</span>(<span class="fu">st_coordinates</span>(mc)))</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">sqrt</span>(<span class="fu">sum</span>((xy[, <span class="dv">1</span>] <span class="sc">-</span> mc_xy[<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (xy[, <span class="dv">2</span>] <span class="sc">-</span> mc_xy[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">nrow</span>(xy)),</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">as.numeric</span>(sd_odl))</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>W analizie używamy funkcji z pakietu <code>sfdep</code>, a nie obliczeń ręcznych — są krótsze, nie da się w nich pomylić indeksu kolumny i zwracają gotowe obiekty przestrzenne. Powyższe porównanie pokazuje jedynie, że nie ma między nimi różnicy.</p>
</section>
</section>
<section id="przykład-2-szkoły-podstawowe-w-poznaniu" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="przykład-2-szkoły-podstawowe-w-poznaniu"><span class="header-section-number">3.4</span> Przykład 2: Szkoły podstawowe w Poznaniu</h2>
<p>W tym przykładzie kod i wyniki są podane, natomiast <strong>interpretacji nie ma w tekście</strong>. Przeczytaj wyniki samodzielnie, odpowiedz na pytania na końcu przykładu, a następnie rozwiń bloki z odpowiedziami i sprawdź swoją interpretację.</p>
<section id="przygotowanie-danych" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="przygotowanie-danych">Przygotowanie danych</h3>
<p>Dane pochodzą z Bazy Danych Obiektów Topograficznych (BDOT10k): warstwa budynków <code>OT_BUBD_A</code> oraz warstwa granic administracyjnych <code>OT_ADJA_A</code>. Kod poniżej pokazuje, jak z nich powstał plik używany w tym i w dwóch kolejnych rozdziałach. Techniki — selekcja atrybutowa, złączenie obiektów, zamiana poligonów na punkty, zapis warstw do geopaczki — opisuje <a href="02_dane_przestrzenne.html" class="quarto-xref"><span>Rozdział 1</span></a> i <a href="C_operacje.html" class="quarto-xref"><span>Załącznik C</span></a>.</p>
<p>Plik wynikowy <code>data/out_poznan_szkoly.gpkg</code> jest dostarczony razem z danymi do skryptu, więc tych kroków nie trzeba powtarzać.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Jedna szkoła, kilka budynków
</div>
</div>
<div class="callout-body-container callout-body">
<p>Warstwa <code>OT_BUBD_A</code> zawiera <strong>budynki</strong>, nie instytucje. Szkoła zajmująca kilka budynków — budynek dydaktyczny, salę gimnastyczną, warsztaty — występuje w niej wielokrotnie. Selekcja po funkcji budynku daje 84 obiekty, ale odpowiadają one <strong>51 szkołom</strong>: 34 szkoły mają jeden budynek, 12 ma dwa, cztery mają od trzech do pięciu, a jedna aż dziesięć.</p>
<p>Gdybyśmy pozostawili 84 punkty, każda analiza rozkładu przestrzennego opisywałaby rozmieszczenie <strong>budynków szkolnych</strong>, a nie szkół — a odległości między budynkami tej samej szkoły (kilkadziesiąt metrów) zdominowałyby wyniki metod opartych na odległości (<a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>).</p>
<p>Dlatego budynki tej samej szkoły scalamy. Kluczem jest atrybut <code>INFORMACJADODATKOWA</code>, który zawiera nazwę szkoły. Funkcja <code>summarise()</code> na obiekcie klasy <code>sf</code> łączy geometrie w obrębie grupy, a <code>st_centroid()</code> zamienia wynik na jeden punkt reprezentujący szkołę.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># granica miasta z warstwy granic administracyjnych</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/bdot10k/PL.PZGiK.308.BDOT10k.3064__OT_ADJA_A.gpkg"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> granica[granica<span class="sc">$</span>RODZAJ <span class="sc">==</span> <span class="st">"powiat"</span>, <span class="st">"geometria"</span>]</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># selekcja budynków szkół podstawowych z warstwy budynków</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>budynki <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/bdot10k/PL.PZGiK.308.BDOT10k.3064__OT_BUBD_A.gpkg"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>budynki_szkol <span class="ot">=</span> budynki <span class="sc">|&gt;</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PRZEWAZAJACAFUNKCJABUDYNKU <span class="sc">==</span> <span class="st">"szkoła podstawowa"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># scalenie budynków tej samej szkoły i zamiana na punkty:</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># INFORMACJADODATKOWA zawiera nazwę szkoły, summarise() łączy geometrie w grupie</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>szkoly <span class="ot">=</span> budynki_szkol <span class="sc">|&gt;</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">nazwa =</span> INFORMACJADODATKOWA) <span class="sc">|&gt;</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">liczba_budynkow =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_centroid</span>()</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(szkoly, <span class="at">dsn =</span> <span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"szkoly"</span>, <span class="at">delete_dsn =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(granica, <span class="at">dsn =</span> <span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"granica"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dane-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dane-1">Dane</h3>
<p>Granica miasta została wczytana już w Przykładzie 1 — w tym przykładzie używamy tego samego obiektu. Dochodzi tylko warstwa punktowa ze szkołami.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>szkoly <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"szkoly"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(szkoly)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(szkoly) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.5</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_punkty_centrograficzne_files/figure-html/p2-dane-b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="krok-1-obliczenie-statystyk-centrograficznych" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-1-obliczenie-statystyk-centrograficznych">Krok 1: obliczenie statystyk centrograficznych</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>sz_mc <span class="ot">=</span> <span class="fu">center_mean</span>(szkoly)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>sz_md <span class="ot">=</span> <span class="fu">center_median</span>(szkoly)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>sz_sd <span class="ot">=</span> <span class="fu">std_distance</span>(szkoly)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par <span class="ot">=</span> <span class="fu">std_dev_ellipse</span>(szkoly)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>sz_sd</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4188.111</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(sz_mc, sz_md)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Units: [m]
         [,1]
[1,] 498.6045</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 358275.3 ymin: 506463.5 xmax: 358275.3 ymax: 506463.5
Projected CRS: ETRF2000-PL / CS92
        sx      sy    theta                  geometry
1 3745.387 4741.78 120.4591 POINT (358275.3 506463.5)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par<span class="sc">$</span>sy <span class="sc">/</span> sz_elipsa_par<span class="sc">$</span>sx</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.266032</code></pre>
</div>
</div>
</section>
<section id="krok-2-wizualizacja" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-2-wizualizacja">Krok 2: wizualizacja</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>sz_okrag <span class="ot">=</span> <span class="fu">st_buffer</span>(sz_mc, sz_sd)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>sz_elipsa <span class="ot">=</span> <span class="fu">st_ellipse</span>(sz_elipsa_par, <span class="at">sx =</span> sz_elipsa_par<span class="sc">$</span>sx, <span class="at">sy =</span> sz_elipsa_par<span class="sc">$</span>sy)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(szkoly) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_okrag) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_elipsa) <span class="sc">+</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_mc) <span class="sc">+</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_md) <span class="sc">+</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06_punkty_centrograficzne_files/figure-html/p2-krok2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Statystyki centrograficzne dla szkół podstawowych w Poznaniu: średnia centralna (czerwony punkt), mediana centralna (niebieski punkt), odległość standardowa (czerwony okrąg), elipsa odchylenia standardowego (zielona linia).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="krok-3-porównanie-z-przestępstwami" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-3-porównanie-z-przestępstwami">Krok 3: porównanie z przestępstwami</h3>
<p>Oba przykłady używają <strong>tej samej granicy</strong> i tego samego obszaru odniesienia, więc wyniki można porównywać bezpośrednio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_area</span>(granica)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>261673672 [m^2]</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>przestępstwa</th>
<th>szkoły</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>liczba punktów</td>
<td>1661</td>
<td>51</td>
</tr>
<tr class="even">
<td>odległość standardowa [m]</td>
<td>3887</td>
<td>4188</td>
</tr>
<tr class="odd">
<td>stosunek osi elipsy</td>
<td>1.08</td>
<td>1.27</td>
</tr>
<tr class="even">
<td>azymut dłuższej osi [°]</td>
<td>136.7</td>
<td>120.5</td>
</tr>
<tr class="odd">
<td>odległość średnia↔︎mediana [m]</td>
<td>255</td>
<td>499</td>
</tr>
</tbody>
</table>
</section>
<section id="sprawdź-swoją-interpretację" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sprawdź-swoją-interpretację">Sprawdź swoją interpretację</h3>
<blockquote class="blockquote">
<p><strong>Pytanie 1.</strong> Odległość standardowa szkół (4188 m) jest większa niż przestępstw (3887 m). Co to znaczy? Czy porównanie tych dwóch liczb jest uprawnione?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Szkoły są <strong>bardziej rozproszone</strong> niż przestępstwa — ich chmura punktów jest przeciętnie szersza względem swojego środka. Ma to sens merytoryczny: szkoły podstawowe rozmieszcza się tak, by obsługiwały całe miasto, w tym osiedla peryferyjne, natomiast przestępstwa koncentrują się w centrum.</p>
<p>Porównanie jest uprawnione, bo <strong>oba zbiory dotyczą tego samego obszaru</strong> — w obu przykładach użyto tej samej warstwy <code>granica</code>, o powierzchni ok. 262 km².</p>
<p>Gdyby obszary były różne, porównywanie odległości standardowych nie miałoby sensu: większy obszar z natury daje większe rozproszenie, niezależnie od tego, jak rozmieszczone są w nim punkty. To warunek, który trzeba sprawdzić <strong>przed</strong> porównaniem, a nie po — i który w analizie dwóch różnych zjawisk w „tym samym mieście” bardzo łatwo przeoczyć, bo granice miasta z dwóch różnych źródeł danych nigdy nie są dokładnie takie same.</p>
<p>Różnica wynosi 301 m, czyli około 8% — jest więc wyraźna, ale nie dramatyczna. Oba zjawiska koncentrują się w tym samym mieście, a szkoły są rozłożone trochę szerzej.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 2.</strong> Elipsa szkół jest wyraźniej wydłużona (stosunek osi 1.27) niż elipsa przestępstw (1.08). Czy to znaczy, że szkoły są bardziej kierunkowo rozmieszczone?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie — i jest to najmniej oczywisty wniosek w tym rozdziale.</p>
<p>Po pierwsze, <strong>oba stosunki są bliskie jedności</strong>. Elipsa o osiach różniących się o 8% i o 27% to w obu przypadkach kształt bliski koła, a dla kształtu bliskiego koła kierunek dłuższej osi nie jest wielkością dobrze określoną.</p>
<p>Po drugie, i ważniejsze: elipsa szkół wyliczona jest z <strong>51 punktów</strong>, a elipsa przestępstw z 1661. Kształt wyliczony z kilkudziesięciu obserwacji jest w dużej mierze dziełem przypadku — wystarczy, że kilka szkół leży na obrzeżach miasta w jednym kierunku, żeby elipsa się wydłużyła. Przy ponad tysiącu punktów taki efekt się nie zdarza.</p>
<p>Czyli: <strong>elipsa, która wygląda na bardziej wydłużoną, niesie mniej informacji, bo opiera się na 33 razy mniejszej liczbie punktów.</strong> To ta sama zasada, co przy czytaniu wykresu pudełkowego razem z liczebnością grup (<a href="04_eksploracja.html" class="quarto-xref"><span>Rozdział 2</span></a>).</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 3.</strong> Azymut dłuższej osi dla szkół wynosi 120.5°, a dla przestępstw 136.7° — różnica wynosi 16.2°. Czy to znaczy, że oba zjawiska mają różny kierunek rozproszenia?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie można tego stwierdzić. Oba stosunki osi są bliskie jedności, a <strong>azymut elipsy niemal kolistej jest wielkością słabo określoną</strong> — przy osiach różniących się o kilka czy dwadzieścia procent niewielka zmiana w położeniu kilku punktów potrafi obrócić dłuższą oś o kilkadziesiąt stopni. Różnica 16.2° między dwiema niemal kolistymi elipsami nie jest więc różnicą kierunku.</p>
<p>Dodatkowo azymut elipsy przestępstw pokrywa się z kierunkiem wydłużenia samego Poznania, co widać na mapie — a to kolejny powód, by go nie czytać jako właściwości zjawiska.</p>
<p>Zasada: kierunek elipsy interpretuje się tylko wtedy, gdy elipsa jest <strong>wyraźnie wydłużona</strong> i gdy jej kierunek <strong>nie pokrywa się</strong> z kierunkiem obszaru badań. W pozostałych przypadkach azymut jest liczbą, którą funkcja zwraca, ale która nie opisuje niczego istotnego.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 4.</strong> Odległość między średnią a medianą centralną wynosi dla szkół 499 m, a dla przestępstw 255 m. Czy dla szkół średnia centralna jest zaburzona przez nietypowe lokalizacje?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie. Liczbę metrów trzeba odnieść do skali rozproszenia zbioru, a nie oceniać bezwzględnie. Dla szkół odległość między środkami stanowi 12% odległości standardowej, dla przestępstw 7%. W obu przypadkach jest to wartość niewielka, więc oba środki opisują to samo położenie i średnia centralna jest bezpieczną miarą.</p>
<p>Bezwzględnie większa odległość dla szkół (499 m wobec 255 m) wynika głównie z tego, że przy 51 punktach mediana współrzędnych jest mniej stabilna niż przy 1661 — nie z obecności lokalizacji skrajnych.</p>
</div>
</div>
</div>
</section>
</section>
<section id="pytania-kontrolne" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="pytania-kontrolne"><span class="header-section-number">3.5</span> Pytania kontrolne</h2>
<blockquote class="blockquote">
<p><strong>1.</strong> Na jakie pytania badawcze odpowiadają statystyki centrograficzne?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Na pytania o <strong>położenie środkowe</strong>, <strong>wielkość rozproszenia</strong> i <strong>kierunek rozproszenia</strong> zbioru punktów traktowanego jako całość.</p>
<p>Pytanie o typ rozkładu — losowy, skupiony czy regularny — wymaga zbadania relacji między poszczególnymi punktami i należy do metod opartych na intensywności (<a href="07_punkty_intensywnosc.html" class="quarto-xref"><span>Rozdział 4</span></a>) oraz na odległości (<a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>).</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>2.</strong> Czym różni się średnia centralna od mediany centralnej i po co liczyć obie?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Średnia centralna to punkt o współrzędnych będących <strong>średnimi arytmetycznymi</strong> współrzędnych, mediana centralna — <strong>medianami</strong> współrzędnych, wyznaczanymi osobno dla każdej osi. Mediana jest odporna na wartości skrajne.</p>
<p>Obie liczy się po to, żeby je porównać. Jeśli leżą blisko siebie (w stosunku do odległości standardowej), średnia centralna dobrze opisuje położenie zbioru. Jeśli są wyraźnie odległe, w zbiorze są lokalizacje skrajne przeciągające średnią i lepszym opisem jest mediana.</p>
<p>Uwaga terminologiczna: tak zdefiniowana mediana centralna <strong>nie jest</strong> punktem minimalizującym sumę odległości do wszystkich punktów, czyli medianą geometryczną.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>3.</strong> W jakich jednostkach wyrażona jest odległość standardowa i od czego to zależy?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>W jednostkach układu współrzędnych, w którym zapisane są dane. Dla danych w układzie odwzorowanym, takim jak PUWG 1992 (<code>EPSG:2180</code>), są to <strong>metry</strong>. Dla danych w układzie współrzędnych geograficznych byłyby to <strong>stopnie</strong>, co czyni wynik bezużytecznym — dlatego przed obliczeniem statystyk centrograficznych dane należy przekształcić do układu odwzorowanego (<a href="02_dane_przestrzenne.html" class="quarto-xref"><span>Rozdział 1</span></a>).</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>4.</strong> Dlaczego liczba „odległość standardowa = 3887 m” sama w sobie niczego nie opisuje?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Bo nie ma do czego jej odnieść. Ta sama liczba oznacza silne skupienie w obszarze o średnicy 50 km i rozproszenie w obszarze o średnicy 5 km. Potrzebny jest punkt odniesienia: wartość dla innego zbioru w tym samym obszarze albo dla tego samego zbioru w innym okresie.</p>
<p>W tym rozdziale punktem odniesienia był drugi zbiór: szkoły podstawowe w tym samym mieście, dla których odległość standardowa wynosi 4188 m. Dopiero to porównanie pozwala powiedzieć, że przestępstwa są rozłożone ciaśniej niż szkoły.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>5.</strong> Dlaczego kierunek elipsy odchylenia standardowego trzeba porównać z kształtem obszaru badań?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ponieważ punkty leżą wewnątrz obszaru, a jeśli obszar jest wydłużony, to wydłużenie przenosi się na elipsę — niezależnie od tego, jak punkty są w nim rozmieszczone. Granica Poznania jest wydłużona w kierunku NW–SE i azymut elipsy przestępstw (136.7°) wskazuje dokładnie ten kierunek. Wniosek „przestępstwa układają się w kierunku NW–SE” byłby więc wnioskiem o kształcie miasta, nie o przestępczości.</p>
<p>Porównanie jest proste: elipsa i granica są na tej samej mapie.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>6.</strong> Dlaczego elipsa wyliczona z 51 punktów jest mniej wiarygodna niż elipsa wyliczona z 1661 punktów, nawet jeśli wygląda na bardziej wydłużoną?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Bo przy małej liczbie punktów kształt elipsy w dużej mierze zależy od przypadku. Wystarczy, że kilka z 51 szkół leży na obrzeżach miasta w jednym kierunku, żeby elipsa wyraźnie się wydłużyła. Przy 1661 punktach pojedyncze lokalizacje nie mają takiego wpływu — elipsa opisuje wtedy rzeczywisty kształt chmury punktów.</p>
<p>To ta sama zasada, którą stosowaliśmy do wykresu pudełkowego w <a href="04_eksploracja.html" class="quarto-xref"><span>Rozdział 2</span></a>: kształt wyliczony z małej liczby obserwacji trzeba czytać razem z tą liczbą.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>7.</strong> Które dwie funkcje <code>sfdep</code> zwracają liczby, a nie geometrię, i jak umieścić ich wynik na mapie?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>std_distance()</code> zwraca jedną liczbę — odległość w jednostkach układu współrzędnych. Aby narysować ją jako okrąg, tworzy się strefę buforową wokół średniej centralnej: <code>st_buffer(mc, sd_odl)</code>.</p>
<p><code>std_dev_ellipse()</code> zwraca parametry <code>sx</code>, <code>sy</code>, <code>theta</code>. Obiekt liniowy do narysowania tworzy funkcja <code>st_ellipse()</code>.</p>
<p>Funkcje <code>center_mean()</code> i <code>center_median()</code> zwracają gotowe obiekty punktowe i można je podać wprost do <code>tm_shape()</code>.</p>
</div>
</div>
</div>
</section>
<section id="podsumowanie" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="podsumowanie"><span class="header-section-number">3.6</span> Podsumowanie</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Statystyka</th>
<th>Funkcja</th>
<th>Co mówi o danych</th>
<th>Warunek poprawnego odczytu</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>średnia centralna</td>
<td><code>center_mean()</code></td>
<td>położenie środkowe zbioru</td>
<td>wrażliwa na lokalizacje skrajne — czytana razem z medianą centralną</td>
</tr>
<tr class="even">
<td>mediana centralna</td>
<td><code>center_median()</code></td>
<td>położenie środkowe odporne na lokalizacje skrajne</td>
<td>jest medianą współrzędnych liczoną osobno dla każdej osi, nie medianą geometryczną</td>
</tr>
<tr class="odd">
<td>odległość standardowa</td>
<td><code>std_distance()</code></td>
<td>wielkość rozproszenia wokół średniej centralnej, w jednostkach układu</td>
<td>wymaga punktu odniesienia: innego zbioru albo innego okresu</td>
</tr>
<tr class="even">
<td>elipsa odchylenia standardowego</td>
<td><code>std_dev_ellipse()</code> + <code>st_ellipse()</code></td>
<td>rozproszenie rozdzielone na dwa prostopadłe kierunki</td>
<td>kierunek jest wiarygodny przy wyraźnym wydłużeniu i po porównaniu z kształtem obszaru</td>
</tr>
</tbody>
</table>
<p>Trzy zasady, do których wracamy w kolejnych rozdziałach:</p>
<ol type="1">
<li><strong>Statystyka centrograficzna wymaga punktu odniesienia.</strong> Liczba sama w sobie nie jest interpretowalna — porównujemy ją z wartością dla innego zbioru w tym samym obszarze albo dla tego samego zbioru w innym okresie.</li>
<li><strong>Przed porównaniem dwóch zbiorów sprawdź, czy dotyczą tego samego obszaru.</strong> Większy obszar z natury daje większe rozproszenie.</li>
<li><strong>Kształt wyliczony z małej liczby punktów czytaj razem z tą liczbą.</strong> Im mniej punktów, tym szerszy zakres wartości, które daje sam przypadek.</li>
</ol>
</section>
<section id="pytania-dla-dwóch-kolejnych-rozdziałów" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="pytania-dla-dwóch-kolejnych-rozdziałów"><span class="header-section-number">3.7</span> Pytania dla dwóch kolejnych rozdziałów</h2>
<p>Cztery policzone w tym rozdziale statystyki opisują zbiór punktów jako całość: gdzie leży jego środek, jak szerokie jest rozproszenie i czy ma ono wyraźny kierunek. Typ rozkładu — losowy, skupiony czy regularny — jest własnością <strong>relacji między poszczególnymi punktami</strong>, więc wymaga innych narzędzi. Dwa zbiory o identycznej średniej centralnej i identycznej odległości standardowej mogą być skrajnie różne: jeden równomiernie rozłożony, drugi zebrany w kilka ciasnych skupień.</p>
<p>Porównanie danych obserwowanych z rozkładem losowym jest zadaniem metod z dwóch kolejnych rozdziałów:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Pytanie</th>
<th>Metoda</th>
<th>Rozdział</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Czy intensywność punktów jest stała w obszarze?</td>
<td>test zliczania w kwadratach</td>
<td><a href="07_punkty_intensywnosc.html" class="quarto-xref"><span>Rozdział 4</span></a></td>
</tr>
<tr class="even">
<td>Gdzie są obszary zagęszczenia?</td>
<td>estymacja gęstości jądra</td>
<td><a href="07_punkty_intensywnosc.html" class="quarto-xref"><span>Rozdział 4</span></a></td>
</tr>
<tr class="odd">
<td>Czy punkty leżą bliżej siebie, niż wynikałoby z przypadku?</td>
<td>statystyki najbliższego sąsiada, wskaźnik Clarka-Evansa</td>
<td><a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a></td>
</tr>
<tr class="even">
<td>Czy odstępstwo od losowości jest istotne statystycznie?</td>
<td>funkcja G z obwiednią</td>
<td><a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Statystyk centrograficznych nie porównujemy z rozkładem losowym
</div>
</div>
<div class="callout-body-container callout-body">
<p>Odległość standardowa 3887 m nabiera znaczenia dopiero po zestawieniu z inną liczbą, więc kuszące jest wylosowanie punktów w tym samym obszarze i porównanie z nimi. <strong>Właściwy tok postępowania jest inny.</strong> Jednorazowe wylosowanie punktów nie jest testem statystycznym, a wniosek wyciągnięty z takiego porównania nie ma określonej wiarygodności.</p>
<p>Porównanie z rozkładem losowym wymaga właściwego narzędzia — wielokrotnej symulacji i obwiedni — i jest treścią <a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>. Statystyki centrograficzne liczymy dla danych i porównujemy <strong>między zbiorami danych</strong>, tak jak w tym rozdziale porównaliśmy przestępstwa ze szkołami.</p>
</div>
</div>
</section>
<section id="pełny-kod-analizy" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="pełny-kod-analizy"><span class="header-section-number">3.8</span> Pełny kod analizy</h2>
<p>Poniżej zebrany jest cały kod obu przykładów, w kolejności wykonania — do skopiowania do własnego skryptu zamiast przeklejania pojedynczych fragmentów. Nie ma w nim kodu objaśniającego: to dokładnie ta ścieżka, która prowadzi od danych wejściowych do wyniku. Przykład 2 korzysta z obiektów utworzonych w Przykładzie 1, więc kod uruchamia się w całości, od początku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sfdep)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>p2019 <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/przestepstwa_2019.gpkg"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"granica"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(p2019)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>mc <span class="ot">=</span> <span class="fu">center_mean</span>(p2019)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>mc</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>md <span class="ot">=</span> <span class="fu">center_median</span>(p2019)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>md</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(mc, md)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>sd_odl <span class="ot">=</span> <span class="fu">std_distance</span>(p2019)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>sd_odl</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>sd_okrag <span class="ot">=</span> <span class="fu">st_buffer</span>(mc, sd_odl)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>elipsa_par <span class="ot">=</span> <span class="fu">std_dev_ellipse</span>(p2019)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>elipsa_par</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>elipsa_par<span class="sc">$</span>sy <span class="sc">/</span> elipsa_par<span class="sc">$</span>sx</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>elipsa <span class="ot">=</span> <span class="fu">st_ellipse</span>(elipsa_par, <span class="at">sx =</span> elipsa_par<span class="sc">$</span>sx, <span class="at">sy =</span> elipsa_par<span class="sc">$</span>sy)</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sd_okrag) <span class="sc">+</span></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(elipsa) <span class="sc">+</span></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(mc) <span class="sc">+</span></span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(md) <span class="sc">+</span></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a>szkoly <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"szkoly"</span>)</span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(szkoly)</span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(szkoly) <span class="sc">+</span></span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.5</span>)</span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a>sz_mc <span class="ot">=</span> <span class="fu">center_mean</span>(szkoly)</span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a>sz_md <span class="ot">=</span> <span class="fu">center_median</span>(szkoly)</span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>sz_sd <span class="ot">=</span> <span class="fu">std_distance</span>(szkoly)</span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par <span class="ot">=</span> <span class="fu">std_dev_ellipse</span>(szkoly)</span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a>sz_sd</span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(sz_mc, sz_md)</span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par</span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a>sz_elipsa_par<span class="sc">$</span>sy <span class="sc">/</span> sz_elipsa_par<span class="sc">$</span>sx</span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a>sz_okrag <span class="ot">=</span> <span class="fu">st_buffer</span>(sz_mc, sz_sd)</span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a>sz_elipsa <span class="ot">=</span> <span class="fu">st_ellipse</span>(sz_elipsa_par, <span class="at">sx =</span> sz_elipsa_par<span class="sc">$</span>sx, <span class="at">sy =</span> sz_elipsa_par<span class="sc">$</span>sy)</span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span></span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(szkoly) <span class="sc">+</span></span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb47-60"><a href="#cb47-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_okrag) <span class="sc">+</span></span>
<span id="cb47-61"><a href="#cb47-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-62"><a href="#cb47-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_elipsa) <span class="sc">+</span></span>
<span id="cb47-63"><a href="#cb47-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-64"><a href="#cb47-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_mc) <span class="sc">+</span></span>
<span id="cb47-65"><a href="#cb47-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-66"><a href="#cb47-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sz_md) <span class="sc">+</span></span>
<span id="cb47-67"><a href="#cb47-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)</span>
<span id="cb47-68"><a href="#cb47-68" aria-hidden="true" tabindex="-1"></a><span class="fu">st_area</span>(granica)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Skopiowano!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Skopiowano!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05_punkty_teoria.html" class="pagination-link" aria-label="DANE PUNKTOWE">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">DANE PUNKTOWE</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07_punkty_intensywnosc.html" class="pagination-link" aria-label="Metody oparte na analizie intensywności">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>