<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Metody oparte na analizie intensywności – Statystyka przestrzenna</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08_punkty_odleglosc.html" rel="next">
<link href="./06_punkty_centrograficzne.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c852b7e71cc1c09f55f367b2512aabbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Brak wyników",
    "search-matching-documents-text": "dopasowane dokumenty",
    "search-copy-link-title": "Kopiuj link do wyszukiwania",
    "search-hide-matches-text": "Ukryj dodatkowe dopasowania",
    "search-more-match-text": "więcej dopasowań w tym dokumencie",
    "search-more-matches-text": "więcej dopasowań w tym dokumencie",
    "search-clear-button-title": "Wyczyść",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Anuluj",
    "search-submit-button-title": "Zatwierdź",
    "search-label": "Szukaj"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_punkty_teoria.html">DANE PUNKTOWE</a></li><li class="breadcrumb-item"><a href="./07_punkty_intensywnosc.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Szukaj" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statystyka przestrzenna</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Szukaj"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O skrypcie</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_wstep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WSTĘP</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_dane_przestrzenne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Dane przestrzenne w R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_eksploracja_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EKSPLORACYJNA ANALIZA DANYCH</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_eksploracja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Eksploracyjna analiza danych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05_punkty_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE PUNKTOWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_punkty_centrograficzne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_punkty_intensywnosc.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_punkty_odleglosc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Metody oparte na odległości</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./09_obszarowe_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE OBSZAROWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_obszarowe_sasiedztwo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Określanie sąsiedztwa danych obszarowych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_obszarowe_autokorelacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Miary autokorelacji danych obszarowych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./12_pola_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE POWIERZCHNIOWE CIĄGŁE PRZESTRZENNIE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_pola_interpolacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Metody interpolacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_pola_semiwariogram.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_pola_estymacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Geostatystyczne metody estymacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_pola_ocena.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Ocena jakości estymacji</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">ZADANIA I PROJEKTY</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_zadania_samodzielne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Zadania samodzielne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_projekt1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Projekt 1: przestępczość a zmienne społeczno-ekonomiczne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_projekt2_geostatystyka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Projekt 2: Geostatystyka</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Załączniki</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A_pakiety.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Pakiety</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B_funkcje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Funkcje</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C_operacje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Operacje na danych przestrzennych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D_slownik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Słownik pojęć</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Spis treści</h2>
   
  <ul>
  <li><a href="#wprowadzenie" id="toc-wprowadzenie" class="nav-link active" data-scroll-target="#wprowadzenie"><span class="header-section-number">4.1</span> Wprowadzenie</a></li>
  <li><a href="#metody-oparte-na-intensywności-w-r" id="toc-metody-oparte-na-intensywności-w-r" class="nav-link" data-scroll-target="#metody-oparte-na-intensywności-w-r"><span class="header-section-number">4.2</span> Metody oparte na intensywności w R</a></li>
  <li><a href="#przykład-1-przestępczość-w-poznaniu" id="toc-przykład-1-przestępczość-w-poznaniu" class="nav-link" data-scroll-target="#przykład-1-przestępczość-w-poznaniu"><span class="header-section-number">4.3</span> Przykład 1: Przestępczość w Poznaniu</a>
  <ul class="collapse">
  <li><a href="#dane" id="toc-dane" class="nav-link" data-scroll-target="#dane">Dane</a></li>
  <li><a href="#krok-1-przekształcenie-na-obiekt-klasy-ppp" id="toc-krok-1-przekształcenie-na-obiekt-klasy-ppp" class="nav-link" data-scroll-target="#krok-1-przekształcenie-na-obiekt-klasy-ppp">Krok 1: przekształcenie na obiekt klasy ppp</a></li>
  <li><a href="#krok-2-średnia-intensywność" id="toc-krok-2-średnia-intensywność" class="nav-link" data-scroll-target="#krok-2-średnia-intensywność">Krok 2: średnia intensywność</a></li>
  <li><a href="#krok-3-wpływ-wyboru-okna-analizy" id="toc-krok-3-wpływ-wyboru-okna-analizy" class="nav-link" data-scroll-target="#krok-3-wpływ-wyboru-okna-analizy">Krok 3: wpływ wyboru okna analizy</a></li>
  <li><a href="#krok-4-zliczanie-punktów-w-siatce" id="toc-krok-4-zliczanie-punktów-w-siatce" class="nav-link" data-scroll-target="#krok-4-zliczanie-punktów-w-siatce">Krok 4: zliczanie punktów w siatce</a></li>
  <li><a href="#krok-5-test-zliczania-w-kwadratach" id="toc-krok-5-test-zliczania-w-kwadratach" class="nav-link" data-scroll-target="#krok-5-test-zliczania-w-kwadratach">Krok 5: test zliczania w kwadratach</a></li>
  <li><a href="#krok-6-analiza-gęstości-jądra" id="toc-krok-6-analiza-gęstości-jądra" class="nav-link" data-scroll-target="#krok-6-analiza-gęstości-jądra">Krok 6: analiza gęstości jądra</a></li>
  <li><a href="#interpretacja-wyniku" id="toc-interpretacja-wyniku" class="nav-link" data-scroll-target="#interpretacja-wyniku">Interpretacja wyniku</a></li>
  </ul></li>
  <li><a href="#przykład-2-rozkład-przestrzenny-szkół-podstawowych-w-poznaniu" id="toc-przykład-2-rozkład-przestrzenny-szkół-podstawowych-w-poznaniu" class="nav-link" data-scroll-target="#przykład-2-rozkład-przestrzenny-szkół-podstawowych-w-poznaniu"><span class="header-section-number">4.4</span> Przykład 2: Rozkład przestrzenny szkół podstawowych w Poznaniu</a>
  <ul class="collapse">
  <li><a href="#dane-1" id="toc-dane-1" class="nav-link" data-scroll-target="#dane-1">Dane</a></li>
  <li><a href="#krok-1-średnia-intensywność" id="toc-krok-1-średnia-intensywność" class="nav-link" data-scroll-target="#krok-1-średnia-intensywność">Krok 1: średnia intensywność</a></li>
  <li><a href="#krok-2-zliczanie-punktów-w-siatce" id="toc-krok-2-zliczanie-punktów-w-siatce" class="nav-link" data-scroll-target="#krok-2-zliczanie-punktów-w-siatce">Krok 2: zliczanie punktów w siatce</a></li>
  <li><a href="#krok-3-test-zliczania-w-kwadratach-dla-dwóch-siatek" id="toc-krok-3-test-zliczania-w-kwadratach-dla-dwóch-siatek" class="nav-link" data-scroll-target="#krok-3-test-zliczania-w-kwadratach-dla-dwóch-siatek">Krok 3: test zliczania w kwadratach dla dwóch siatek</a></li>
  <li><a href="#krok-4-analiza-gęstości-jądra" id="toc-krok-4-analiza-gęstości-jądra" class="nav-link" data-scroll-target="#krok-4-analiza-gęstości-jądra">Krok 4: analiza gęstości jądra</a></li>
  <li><a href="#sprawdź-swoją-interpretację" id="toc-sprawdź-swoją-interpretację" class="nav-link" data-scroll-target="#sprawdź-swoją-interpretację">Sprawdź swoją interpretację</a></li>
  </ul></li>
  <li><a href="#pytania-kontrolne" id="toc-pytania-kontrolne" class="nav-link" data-scroll-target="#pytania-kontrolne"><span class="header-section-number">4.5</span> Pytania kontrolne</a></li>
  <li><a href="#podsumowanie" id="toc-podsumowanie" class="nav-link" data-scroll-target="#podsumowanie"><span class="header-section-number">4.6</span> Podsumowanie</a></li>
  <li><a href="#pytanie-dla-kolejnego-rozdziału" id="toc-pytanie-dla-kolejnego-rozdziału" class="nav-link" data-scroll-target="#pytanie-dla-kolejnego-rozdziału"><span class="header-section-number">4.7</span> Pytanie dla kolejnego rozdziału</a></li>
  <li><a href="#pełny-kod-analizy" id="toc-pełny-kod-analizy" class="nav-link" data-scroll-target="#pełny-kod-analizy"><span class="header-section-number">4.8</span> Pełny kod analizy</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_punkty_teoria.html">DANE PUNKTOWE</a></li><li class="breadcrumb-item"><a href="./07_punkty_intensywnosc.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-punkty-intensywnosc" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Czego się nauczysz
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Po tym rozdziale potrafisz wykonać w R:</strong></p>
<ul>
<li>przekształcić dane punktowe na obiekt klasy <code>ppp</code> wraz z oknem analizy,</li>
<li>obliczyć średnią intensywność i przeskalować ją do czytelnych jednostek,</li>
<li>zliczyć punkty w siatce — funkcją pakietu <code>spatstat</code> oraz na obiekcie <code>sf</code>,</li>
<li>wykonać test zliczania w kwadratach,</li>
<li>wykonać analizę gęstości jądra dla różnych szerokości pasma,</li>
<li>przedstawić wyniki na mapach w pakiecie <code>tmap</code>.</li>
</ul>
<p><strong>Rozumiesz i umiesz zinterpretować:</strong></p>
<ul>
<li>dlaczego średnia intensywność zależy od <strong>wyboru okna analizy</strong> i jak silnie,</li>
<li>dlaczego liczba oczek siatki zmienia wynik testu zliczania — <strong>skala a zdolność wykrywania struktury</strong>,</li>
<li>warunek stosowalności testu chi-kwadrat (<span class="math inline">\(E_i &gt; 5\)</span>) i co zrobić, gdy nie jest spełniony,</li>
<li>dlaczego szerokość pasma (<code>sigma</code>) zmienia obraz gęstości jądra i że jest wyborem analityka,</li>
<li>że wszystkie trzy metody opisują intensywność względem <strong>przyjętych założeń</strong>, a nie bezwzględnie.</li>
</ul>
<p><strong>Teoria:</strong> <a href="./05_punkty_teoria.html#najwazniejsze-punkty">Najważniejsze informacje</a>. <strong>Funkcje:</strong> <a href="B_funkcje.html" class="quarto-xref"><span>Załącznik B</span></a>.</p>
</div>
</div>
<section id="wprowadzenie" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="wprowadzenie"><span class="header-section-number">4.1</span> Wprowadzenie</h2>
<p>W analizie intensywności rozkład przestrzenny punktów charakteryzowany jest <strong>względem określonego obszaru badań</strong> — na przykład granicy miasta. Podstawową miarą jest gęstość <span class="math inline">\(\lambda\)</span>, czyli liczba zdarzeń na jednostkę powierzchni:</p>
<p><span class="math display">\[\hat{\lambda} = \frac{n}{a}\]</span></p>
<p>Statystyki centrograficzne (<a href="06_punkty_centrograficzne.html" class="quarto-xref"><span>Rozdział 3</span></a>) opisywały zbiór punktów przez jego środek i rozproszenie, nie odnosząc się do obszaru. Metody oparte na intensywności zmieniają punkt widzenia: pytają, <strong>ile zdarzeń wypada na jednostkę powierzchni</strong> i czy ta liczba jest w obszarze stała.</p>
<p>Z tego wynika właściwość, która przewija się przez cały rozdział: <strong>każdy wynik zależy od przyjętych założeń</strong>. Średnia intensywność zależy od tego, jaki obszar uznamy za obszar badań. Wynik testu zliczania zależy od tego, na ile oczek go podzielimy. Obraz gęstości jądra zależy od przyjętej szerokości pasma. Żadne z tych trzech założeń nie wynika z danych — wybiera je analityk i musi je podać razem z wynikiem.</p>
</section>
<section id="metody-oparte-na-intensywności-w-r" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="metody-oparte-na-intensywności-w-r"><span class="header-section-number">4.2</span> Metody oparte na intensywności w R</h2>
<p>Obliczenia wymagają przekształcenia danych na obiekt klasy <code>ppp</code> (ang. <em>planar point pattern</em>) wraz ze zdefiniowaniem <strong>okna analizy</strong> (ang. <em>window</em>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Funkcja</th>
<th>Co robi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>spatstat::as.owin()</code></td>
<td>tworzy okno analizy na podstawie innego obiektu (np. granicy miasta)</td>
</tr>
<tr class="even">
<td><code>spatstat::as.ppp()</code></td>
<td>przekształca dane punktowe na obiekt klasy <code>ppp</code>; wymaga podania okna</td>
</tr>
<tr class="odd">
<td><code>spatstat::rescale()</code></td>
<td>przeskalowuje obiekt <code>ppp</code> do innych jednostek (np. z metrów na kilometry)</td>
</tr>
<tr class="even">
<td><code>summary()</code> na obiekcie <code>ppp</code></td>
<td>podaje liczbę punktów, powierzchnię okna oraz średnią intensywność</td>
</tr>
<tr class="odd">
<td><code>spatstat::quadratcount()</code></td>
<td>zlicza punkty w oczkach siatki</td>
</tr>
<tr class="even">
<td><code>spatstat::quadrat.test()</code></td>
<td>test zliczania w kwadratach; <code>method = "MonteCarlo"</code> gdy wartości oczekiwane są małe</td>
</tr>
<tr class="odd">
<td><code>spatstat::density()</code></td>
<td>analiza gęstości jądra; wynik przekształcamy na raster funkcją <code>terra::rast()</code></td>
</tr>
</tbody>
</table>
<p>Pełne zestawienie funkcji — <a href="B_funkcje.html" class="quarto-xref"><span>Załącznik B</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dlaczego nie <code>library(terra)</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pakiet <code>terra</code> zawiera własne funkcje <code>rescale()</code>, <code>density()</code> i <code>area()</code> — o takich samych nazwach jak funkcje z pakietu <code>spatstat</code>, ale przeznaczone dla danych rastrowych. Po wywołaniu <code>library(terra)</code> <strong>zasłaniają</strong> one funkcje <code>spatstat</code>, a <code>rescale()</code> na obiekcie klasy <code>ppp</code> przestaje działać w ogóle.</p>
<p>W tym rozdziale <code>terra</code> jest potrzebny tylko do zamiany wyniku analizy gęstości jądra na raster, dlatego wywołujemy go z przedrostkiem nazwy pakietu (<code>terra::rast()</code>) i nie ładujemy funkcją <code>library()</code>.</p>
</div>
</div>
</section>
<section id="przykład-1-przestępczość-w-poznaniu" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="przykład-1-przestępczość-w-poznaniu"><span class="header-section-number">4.3</span> Przykład 1: Przestępczość w Poznaniu</h2>
<section id="dane" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dane">Dane</h3>
<ul>
<li><code>data/przestepstwa_2019.gpkg</code> — lokalizacje przestępstw w Poznaniu w 2019 roku; warstwa punktowa bez atrybutów,</li>
<li><code>data/out_poznan_szkoly.gpkg</code>, warstwa <code>granica</code> — granica miasta Poznania. Ta sama granica jest używana w <a href="06_punkty_centrograficzne.html" class="quarto-xref"><span>Rozdział 3</span></a> oraz w Przykładzie 2, więc wyniki można porównywać bezpośrednio.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>p2019 <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/przestepstwa_2019.gpkg"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"granica"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(p2019)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1661</code></pre>
</div>
</div>
</section>
<section id="krok-1-przekształcenie-na-obiekt-klasy-ppp" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-1-przekształcenie-na-obiekt-klasy-ppp">Krok 1: przekształcenie na obiekt klasy ppp</h3>
<p>Funkcje pakietu <code>spatstat</code> nie działają na obiektach <code>sf</code>. Potrzebne są dwa przekształcenia: granica staje się <strong>oknem analizy</strong> (klasa <code>owin</code>), a punkty — <strong>wzorem punktowym</strong> (klasa <code>ppp</code>) zdefiniowanym w tym oknie.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pzn_owin <span class="ot">=</span> <span class="fu">as.owin</span>(granica)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p2019_ppp <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(p2019), <span class="at">W =</span> pzn_owin)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>p2019_ppp</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern: 1661 points
window: polygonal boundary
enclosing rectangle: [345943.2, 368927.8] x [493660, 517878.9] units</code></pre>
</div>
</div>
<p>Wypisany obiekt podaje liczbę punktów oraz zasięg okna. Pełniejszy opis daje funkcja <code>summary()</code>: liczbę punktów, <strong>powierzchnię okna</strong> (<em>window area</em>) oraz <strong>średnią intensywność</strong> (<em>average intensity</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  1661 points
Average intensity 6.347601e-06 points per square unit

Coordinates are given to 10 decimal places

Window: polygonal boundary
single connected closed polygon with 3395 vertices
enclosing rectangle: [345943.2, 368927.8] x [493660, 517878.9] units
                     (22980 x 24220 units)
Window area = 261674000 square units
Fraction of frame area: 0.47</code></pre>
</div>
</div>
</section>
<section id="krok-2-średnia-intensywność" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-2-średnia-intensywność">Krok 2: średnia intensywność</h3>
<p>Intensywność z poprzedniego kroku jest wyrażona w punktach na <strong>metr kwadratowy</strong>, bo dane są w układzie PUWG 1992 (<code>EPSG:2180</code>), którego jednostką jest metr. Liczba rzędu 0,000006 jest nieczytelna, dlatego obiekt przeskalowujemy z metrów na kilometry funkcją <code>rescale()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p2019_ppp_km <span class="ot">=</span> <span class="fu">rescale</span>(p2019_ppp, <span class="dv">1000</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_km)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  1661 points
Average intensity 6.347601 points per square unit

Coordinates are given to 13 decimal places

Window: polygonal boundary
single connected closed polygon with 3395 vertices
enclosing rectangle: [345.9432, 368.9278] x [493.66, 517.8789] units
                     (22.98 x 24.22 units)
Window area = 261.674 square units
Fraction of frame area: 0.47</code></pre>
</div>
</div>
<p>Samą wartość intensywności można wydobyć bezpośrednio:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_km)<span class="sc">$</span>intensity</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.347601</code></pre>
</div>
</div>
</section>
<section id="krok-3-wpływ-wyboru-okna-analizy" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-3-wpływ-wyboru-okna-analizy">Krok 3: wpływ wyboru okna analizy</h3>
<p>Intensywność jest ilorazem liczby punktów i powierzchni, więc zmiana obszaru badań zmienia wynik — przy identycznym zbiorze punktów. Poniżej jako okno przyjmujemy <strong>obwiednię</strong> warstwy (<em>bounding box</em>) zamiast granicy miasta.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pzn_owin_bb <span class="ot">=</span> <span class="fu">as.owin</span>(<span class="fu">st_bbox</span>(granica))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>p2019_ppp_bb <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(p2019), <span class="at">W =</span> pzn_owin_bb)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>p2019_ppp_bb_km <span class="ot">=</span> <span class="fu">rescale</span>(p2019_ppp_bb, <span class="dv">1000</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_bb_km)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  1661 points
Average intensity 2.983861 points per square unit

Coordinates are given to 13 decimal places

Window: rectangle = [345.9432, 368.9278] x [493.66, 517.8789] units
                    (22.98 x 24.22 units)
Window area = 556.661 square units</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>obwiednia <span class="ot">=</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(granica))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(obwiednia) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">fill =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok3b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Szary prostokąt to obwiednia warstwy, niebieska linia — granica miasta. Wszystkie punkty leżą w granicy miasta, ale obwiednia obejmuje dodatkowo obszary, na których żadnego punktu nie ma.</p>
</section>
<section id="krok-4-zliczanie-punktów-w-siatce" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-4-zliczanie-punktów-w-siatce">Krok 4: zliczanie punktów w siatce</h3>
<p>Intensywność może nie być stała w całym obszarze, a zmieniać się wraz z lokalizacją. Do zliczenia punktów w siatce służy funkcja <code>quadratcount()</code>; argumenty <code>nx</code> i <code>ny</code> określają liczbę oczek w kierunku poziomym i pionowym.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p2019_count <span class="ot">=</span> <span class="fu">quadratcount</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p2019_count</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tile
Tile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 2, col 1 
                2                14                61                 8 
Tile row 2, col 2 Tile row 2, col 3 Tile row 2, col 4 Tile row 3, col 1 
              200               636                26                11 
Tile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 Tile row 4, col 2 
              230               408                48                 0 
Tile row 4, col 3 Tile row 4, col 4 
               15                 2 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p2019_count, <span class="at">main =</span> <span class="st">"Liczba przestępstw w oczkach siatki"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok4b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Siatka 4×4 ma 16 oczek, ale wynik zawiera <strong>14 wartości</strong>. Dwa oczka leżą w całości poza granicą miasta, a funkcja <code>quadratcount()</code> przycina siatkę do okna analizy. Ma to znaczenie w kroku 5: liczba stopni swobody testu wynosi liczba oczek minus jeden, czyli 13, a nie 15.</p>
<section id="siatka-jako-obiekt-przestrzenny" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="siatka-jako-obiekt-przestrzenny">Siatka jako obiekt przestrzenny</h4>
<p>Wynik <code>quadratcount()</code> można przedstawić graficznie funkcją <code>plot()</code>, ale do bardziej rozbudowanej mapy wygodniej jest utworzyć siatkę jako obiekt pakietu <code>sf</code>. Tworzenie siatki składa się z trzech kroków (<a href="02_dane_przestrzenne.html" class="quarto-xref"><span>Rozdział 1</span></a>, <a href="C_operacje.html" class="quarto-xref"><span>Załącznik C</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># poligon o zasięgu warstwy z granicą miasta</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pzn_bb <span class="ot">=</span> <span class="fu">st_sf</span>(<span class="at">geom =</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(granica)))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># siatka; argument n określa liczbę oczek w każdym kierunku</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>pzn_grid <span class="ot">=</span> <span class="fu">st_make_grid</span>(pzn_bb, <span class="at">n =</span> <span class="dv">4</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># zamiana siatki na obiekt klasy sf</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf <span class="ot">=</span> <span class="fu">st_sf</span>(<span class="at">geometry =</span> pzn_grid)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pzn_grid_sf)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok4d-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Liczbę punktów w każdym oczku wyznaczamy przez przecięcie siatki z warstwą punktową. Funkcja <code>st_intersects()</code> zwraca listę, w której każdy element odpowiada jednemu oczku i zawiera numery punktów w nim leżących; funkcja <code>lengths()</code> zamienia tę listę na liczbę punktów.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf<span class="sc">$</span>dane <span class="ot">=</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(pzn_grid, p2019))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf<span class="sc">$</span>dane</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   0   0  15   2  11 230 408  48   8 200 636  26   2  14  61   0</code></pre>
</div>
</div>
<p>Siatka <code>sf</code> jest utworzona nad obwiednią, więc ma pełne <strong>16 oczek</strong> — w tym dwa, które <code>quadratcount()</code> odrzucił jako leżące poza miastem. Zliczenia w pozostałych oczkach są identyczne w obu metodach, a suma w obu wynosi 1661, czyli tyle, ile punktów w zbiorze.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(pzn_grid_sf) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"dane"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">n =</span> <span class="dv">4</span>, <span class="at">values =</span> <span class="st">"brewer.yl_gn"</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Liczba punktów"</span>)) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok4f-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="krok-5-test-zliczania-w-kwadratach" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-5-test-zliczania-w-kwadratach">Krok 5: test zliczania w kwadratach</h3>
<p>Test zliczania w kwadratach służy do testowania hipotezy zerowej, że punkty są rozmieszczone losowo. Dzieli obszar na oczka, zlicza punkty w każdym z nich i porównuje z wartościami oczekiwanymi przy rozmieszczeniu losowym.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  p2019_ppp
X2 = 1538, df = 13, p-value &lt; 2.2e-16
alternative hypothesis: two.sided

Quadrats: 14 tiles (irregular windows)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ostrzeżenie <code>Some expected counts are small</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Test chi-kwadrat wymaga, aby <strong>wartość oczekiwana w każdym oczku przekraczała 5</strong>. Gdy warunek jest złamany choćby w jednym oczku, <code>spatstat</code> wypisuje ostrzeżenie <code>Some expected counts are small; chi^2 approximation may be inaccurate</code> — i trzeba je przeczytać, bo dotyczy stosowalności testu, nie samego wykonania obliczeń.</p>
<p>Skąd się bierze? Siatka jest przycinana do okna analizy, więc oczka przy granicy miasta mają mniejszą powierzchnię, a wartość oczekiwana jest proporcjonalna do powierzchni oczka. Wartości oczekiwane odczytujemy ze składowej <code>expected</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>qt <span class="ot">=</span> <span class="fu">quadrat.test</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sort</span>(qt<span class="sc">$</span>expected), <span class="dv">2</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   2.44  15.71  43.69  53.21  73.95  77.72 107.46 127.21 165.63 166.29
[11] 173.48 212.53 220.84 220.84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(qt<span class="sc">$</span>expected <span class="sc">&lt;</span> <span class="dv">5</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Dla przestępstw warunek łamie <strong>jedno</strong> oczko z czternastu, a wartość <em>p</em> jest o wiele rzędów wielkości mniejsza od progu istotności — wniosek się zatem nie zmienia. Gdy oczek o małej wartości oczekiwanej jest dużo albo wartość <em>p</em> leży blisko progu, zamiast przybliżenia chi-kwadrat stosuje się wariant oparty na symulacji Monte Carlo (<code>method = "MonteCarlo"</code>). Przykład 2 pokazuje właśnie taki przypadek.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>qtest <span class="ot">=</span> <span class="fu">quadrat.test</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(qtest, <span class="at">main =</span> <span class="st">"Test zliczania w kwadratach"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok5b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na wykresie w każdym oczku podane są trzy liczby: zliczenie obserwowane (u góry po lewej), oczekiwane (u góry po prawej) oraz reszta Pearsona (na dole), czyli znormalizowana różnica między nimi.</p>
</section>
<section id="krok-6-analiza-gęstości-jądra" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-6-analiza-gęstości-jądra">Krok 6: analiza gęstości jądra</h3>
<p>Test zliczania wyznacza lokalną intensywność, dzieląc obszar na oczka o ustalonej wielkości. <strong>Analiza gęstości jądra</strong> (ang. <em>kernel density estimation</em>) używa zamiast tego <strong>ruchomego okna</strong>: dla każdej komórki siatki wynikowej liczy intensywność w otoczeniu o zadanym rozmiarze, wyśrodkowanym na tej komórce. Rozmiar ruchomego okna określa argument <code>sigma</code>, podawany w jednostkach układu współrzędnych — tutaj w metrach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>p2019_kde500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(p2019_ppp, <span class="at">sigma =</span> <span class="dv">500</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(p2019_kde500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(p2019_kde500) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Intensywność"</span>)) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok6a-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>p2019_kde1500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(p2019_ppp, <span class="at">sigma =</span> <span class="dv">1500</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(p2019_kde1500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(p2019_kde1500) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Intensywność"</span>)) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p1-krok6b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretacja-wyniku" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretacja-wyniku">Interpretacja wyniku</h3>
<p><strong>Średnia intensywność.</strong> W granicy miasta o powierzchni 261.7 km² odnotowano 1661 przestępstw, co daje 6.35 przestępstwa na km². Jest to liczba uśredniona dla całego miasta — mówi, ile przestępstw wypada przeciętnie na kilometr kwadratowy, ale nie mówi nic o tym, czy rozkładają się one równomiernie.</p>
<p><strong>Wpływ wyboru okna analizy.</strong> To najważniejsza obserwacja tego przykładu. Przy identycznym zbiorze 1661 punktów intensywność wynosi 6.35 przestępstwa na km² w granicy miasta i 2.98 w obwiedni warstwy. Obwiednia ma 2.13 razy większą powierzchnię (556.7 km² wobec 261.7 km²), a intensywność jest dokładnie 2.13 razy mniejsza — bo licznik jest ten sam, a zmienił się wyłącznie mianownik.</p>
<p>Oba wyniki są poprawnie obliczone i oba są bezużyteczne bez podania okna analizy. Wartość w obwiedni opisuje intensywność przestępstw „na obszarze prostokąta obejmującego Poznań”, w którym mieszczą się tereny nienależące do miasta. Dla zjawiska związanego z zabudową miejską właściwym oknem jest granica administracyjna.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Okno analizy jest częścią wyniku
</div>
</div>
<div class="callout-body-container callout-body">
<p>Średnia intensywność nie jest właściwością zbioru punktów — jest właściwością <strong>pary</strong>: zbioru punktów i obszaru. Podanie liczby bez podania obszaru nie jest wynikiem analizy. W raporcie zawsze zapisuje się, jaki obszar przyjęto za obszar badań i dlaczego.</p>
</div>
</div>
<p><strong>Zmienność w przestrzeni.</strong> Zliczenia w siatce 4×4 wahają się od 0 do 636 punktów na oczko: dwa oczka centralne zawierają po kilkaset przestępstw, a oczka przy granicy miasta po kilka lub kilkanaście. Intensywność nie jest więc stała w obszarze — a to właśnie hipotezę o jej stałości sprawdza test z kroku 5. Wykres testu pokazuje dla każdego oczka zliczenie obserwowane obok oczekiwanego, więc widać na nim bezpośrednio, które oczka odbiegają od wartości oczekiwanej najmocniej. Wynik testu (<em>p</em> &lt; 0,001) prowadzi do odrzucenia hipotezy o losowym rozmieszczeniu przestępstw.</p>
<p><strong>Gęstość jądra.</strong> Obie mapy przedstawiają te same dane i obie są poprawne, ale pokazują zjawisko na różnych skalach. Przy <code>sigma</code> = 500 m widać pojedyncze, wyraźnie odgraniczone ogniska o wysokiej intensywności. Przy <code>sigma</code> = 1500 m obraz jest wygładzony: ogniska zlewają się w jeden rozległy obszar podwyższonej intensywności w centrum miasta, a szczegóły zanikają.</p>
<p>Mniejsza wartość <code>sigma</code> pokazuje strukturę drobnoskalową i jest bardziej wrażliwa na pojedyncze punkty; większa pokazuje tendencję ogólną i tę wrażliwość tłumi. <strong>Żadna z nich nie jest prawdziwsza</strong> — <code>sigma</code> jest wyborem analityka, zależnym od tego, na jakiej skali szukamy struktury, i podaje się ją razem z mapą.</p>
</section>
</section>
<section id="przykład-2-rozkład-przestrzenny-szkół-podstawowych-w-poznaniu" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="przykład-2-rozkład-przestrzenny-szkół-podstawowych-w-poznaniu"><span class="header-section-number">4.4</span> Przykład 2: Rozkład przestrzenny szkół podstawowych w Poznaniu</h2>
<p>W tym przykładzie kod i wyniki są podane, natomiast <strong>interpretacji nie ma w tekście</strong>. Przeczytaj wyniki samodzielnie, odpowiedz na pytania zamieszczone na końcu przykładu, a następnie rozwiń bloki z odpowiedziami i sprawdź poprawność swojej interpretacji.</p>
<section id="dane-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dane-1">Dane</h3>
<p>Granica miasta została wczytana w Przykładzie 1 — używamy tego samego obiektu, a więc i tego samego okna analizy. Dochodzi warstwa punktowa ze szkołami podstawowymi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>szkoly <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"szkoly"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(szkoly)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>szkoly_ppp <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(szkoly), <span class="at">W =</span> pzn_owin)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>szkoly_ppp_km <span class="ot">=</span> <span class="fu">rescale</span>(szkoly_ppp, <span class="dv">1000</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="krok-1-średnia-intensywność" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-1-średnia-intensywność">Krok 1: średnia intensywność</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(szkoly_ppp_km)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  51 points
Average intensity 0.1948992 points per square unit

Coordinates are given to 13 decimal places

Window: polygonal boundary
single connected closed polygon with 3395 vertices
enclosing rectangle: [345.9432, 368.9278] x [493.66, 517.8789] units
                     (22.98 x 24.22 units)
Window area = 261.674 square units
Fraction of frame area: 0.47</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(szkoly_ppp_km)<span class="sc">$</span>intensity</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1948992</code></pre>
</div>
</div>
</section>
<section id="krok-2-zliczanie-punktów-w-siatce" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-2-zliczanie-punktów-w-siatce">Krok 2: zliczanie punktów w siatce</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>szkoly_count <span class="ot">=</span> <span class="fu">quadratcount</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>szkoly_count</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tile
Tile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 2, col 1 
                0                 1                 3                 0 
Tile row 2, col 2 Tile row 2, col 3 Tile row 2, col 4 Tile row 3, col 1 
               11                11                 1                 0 
Tile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 Tile row 4, col 2 
               11                10                 3                 0 
Tile row 4, col 3 Tile row 4, col 4 
                0                 0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(szkoly_count, <span class="at">main =</span> <span class="st">"Liczba szkół w oczkach siatki"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p2-krok2b-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="krok-3-test-zliczania-w-kwadratach-dla-dwóch-siatek" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-3-test-zliczania-w-kwadratach-dla-dwóch-siatek">Krok 3: test zliczania w kwadratach dla dwóch siatek</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  szkoly_ppp
X2 = 27.105, df = 13, p-value = 0.02407
alternative hypothesis: two.sided

Quadrats: 14 tiles (irregular windows)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">2</span>, <span class="at">ny =</span> <span class="dv">2</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  szkoly_ppp
X2 = 5.5251, df = 3, p-value = 0.2743
alternative hypothesis: two.sided

Quadrats: 4 tiles (irregular windows)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quadratcount</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">2</span>, <span class="at">ny =</span> <span class="dv">2</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     x
y                     [3.46e+05,3.57e+05] (3.57e+05,3.69e+05]
  (5.06e+05,5.18e+05]                  12                  15
  [4.94e+05,5.06e+05]                  11                  13</code></pre>
</div>
</div>
<p>Przy 51 punktach warunek stosowalności testu chi-kwadrat trzeba sprawdzić.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>qt_sz <span class="ot">=</span> <span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some expected counts are small; chi^2 approximation may be inaccurate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sort</span>(qt_sz<span class="sc">$</span>expected), <span class="dv">2</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.07 0.48 1.34 1.63 2.27 2.39 3.30 3.91 5.09 5.11 5.33 6.53 6.78 6.78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(qt_sz<span class="sc">$</span>expected <span class="sc">&lt;</span> <span class="dv">5</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>Wariant Monte Carlo nie korzysta z przybliżenia chi-kwadrat, lecz porównuje statystykę testową z rozkładem uzyskanym z symulacji rozmieszczenia losowego. Jest to procedura <strong>losowa</strong>, więc wymaga ustawienia ziarna generatora.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>, <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Conditional Monte Carlo test of CSR using quadrat counts
    Test statistic: Pearson X2 statistic

data:  szkoly_ppp
X2 = 27.105, p-value = 0.05
alternative hypothesis: two.sided

Quadrats: 14 tiles (irregular windows)</code></pre>
</div>
</div>
</section>
<section id="krok-4-analiza-gęstości-jądra" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-4-analiza-gęstości-jądra">Krok 4: analiza gęstości jądra</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>szkoly_kde500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(szkoly_ppp, <span class="at">sigma =</span> <span class="dv">500</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(szkoly_kde500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>szkoly_kde1500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(szkoly_ppp, <span class="at">sigma =</span> <span class="dv">1500</span>))</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(szkoly_kde1500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>mapa500 <span class="ot">=</span> <span class="fu">tm_shape</span>(szkoly_kde500) <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"sigma = 500 m"</span>))</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>mapa1500 <span class="ot">=</span> <span class="fu">tm_shape</span>(szkoly_kde1500) <span class="sc">+</span></span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"sigma = 1500 m"</span>))</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(mapa500, mapa1500)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_punkty_intensywnosc_files/figure-html/p2-krok4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sprawdź-swoją-interpretację" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sprawdź-swoją-interpretację">Sprawdź swoją interpretację</h3>
<blockquote class="blockquote">
<p><strong>Pytanie 1.</strong> Średnia intensywność szkół wynosi 0.195 szkoły na km². Wyraź tę liczbę w sposób czytelny. Czy porównanie jej z intensywnością przestępstw (6.35 na km²) do czegoś prowadzi?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Liczba 0.195 szkoły na km² jest mało czytelna — wygodniej odwrócić ułamek: jedna szkoła podstawowa na 5.13 km² powierzchni miasta.</p>
<p>Porównanie z intensywnością przestępstw <strong>nie prowadzi do żadnego wniosku</strong>. Obie liczby mówią, ile zdarzeń albo obiektów wypada na kilometr kwadratowy, ale dotyczą zjawisk nieporównywalnych: przestępstwo to zdarzenie, szkoła to obiekt infrastruktury. To, że przestępstw jest na km² 33 razy więcej niż szkół, nie jest informacją o żadnym z tych zjawisk.</p>
<p>Sensowne odniesienia dla intensywności szkół to na przykład liczba dzieci w wieku szkolnym, powierzchnia obwodu szkolnego albo intensywność szkół w innym mieście o podobnej wielkości.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 2.</strong> Test dla siatki 4×4 odrzuca hipotezę o losowości, a dla siatki 2×2 — nie. Czy te wyniki są sprzeczne?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie. Oba wyniki są poprawne i <strong>dotyczą różnych skal</strong>.</p>
<p>Zliczenia w siatce 2×2 to 11, 12, 13, 15 — rozkład wygląda równomiernie, bo przy czterech wielkich oczkach skupienia szkół mieszczą się w całości <strong>wewnątrz</strong> pojedynczych oczek. Siatka ich nie rozdziela, więc test nie ma czego wykryć.</p>
<p>Siatka 4×4 jest na tyle drobna, że skupienia trafiają do różnych oczek: zliczenia wahają się od 0 do 11, a część oczek jest pusta. Na tej skali struktura jest widoczna i test odrzuca hipotezę o losowości.</p>
<p><strong>Z jednym zastrzeżeniem</strong>, które trzeba odczytać z kroku 3: przy 51 punktach w 14 oczkach warunek <span class="math inline">\(E_i &gt; 5\)</span> jest złamany w 8 oczkach, a najmniejsza wartość oczekiwana wynosi 0.07. Przybliżenie chi-kwadrat jest tu więc niedokładne i samo <code>spatstat</code> o tym ostrzega. Test Monte Carlo, który tego przybliżenia nie używa, daje wartość <em>p</em> równą 0,05 — czyli <strong>dokładnie na progu istotności</strong>, a nie wyraźnie poniżej niego jak 0,024 z testu chi-kwadrat.</p>
<p>Wniosek nie brzmi więc „szkoły są rozmieszczone losowo” ani „nie są”, lecz: <strong>na skali kilkukilometrowej rozmieszczenie szkół nie odbiega od losowego, a na skali drobniejszej odstępstwo jest na granicy istotności</strong> — i przy tej liczbie punktów mocniejszego wniosku ta metoda nie uprawnia. Pytanie o skalę rozstrzygają metody oparte na odległości (<a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>), które nie dzielą obszaru na oczka.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 3.</strong> Która liczba oczek jest zatem właściwa?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Żadna nie jest „właściwa” w oderwaniu od pytania badawczego. Liczba oczek <strong>określa skalę</strong>, na której szukamy struktury, i jest decyzją analityka — tak jak okno analizy w kroku 3 Przykładu 1 i jak szerokość pasma w analizie gęstości jądra.</p>
<p>Zbyt gruba siatka nie wykryje skupień drobnoskalowych. Zbyt drobna rozdrobni obszar na oczka zawierające po kilka punktów, przy których nawet rozkład równomierny będzie wyglądał nierówno. Praktycznie: liczbę oczek dobiera się do skali zjawiska, które się bada, i <strong>podaje ją w raporcie razem z wynikiem</strong> — wartość p bez informacji o siatce nie jest wynikiem analizy.</p>
<p>Ten sam problem w analizie danych obszarowych nazywa się problemem zmiennych jednostek odniesienia (ang. <em>modifiable areal unit problem</em>, MAUP) i wraca w <a href="11_obszarowe_autokorelacja.html" class="quarto-xref"><span>Rozdział 7</span></a>.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pytanie 4.</strong> Porównaj mapy gęstości jądra dla <code>sigma</code> = 500 m i <code>sigma</code> = 1500 m. Która pokazuje rzeczywisty rozkład szkół?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Obie — na różnych skalach. Mapa dla <code>sigma</code> = 500 m pokazuje pojedyncze szkoły jako odrębne ogniska, bo ruchome okno o promieniu 500 m obejmuje najczęściej jedną szkołę. Mapa dla <code>sigma</code> = 1500 m pokazuje obszary, w których szkół jest więcej niż przeciętnie, a pojedyncze lokalizacje się w niej zacierają.</p>
<p>Przy 51 punktach w mieście o powierzchni 261.7 km² typowa odległość do najbliższej innej szkoły wynosi 644 m (mediana), więc pasmo 500 m jest węższe niż odstęp między punktami — mapa pokazuje wtedy raczej położenie poszczególnych szkół niż strukturę ich rozmieszczenia. Dla tego zbioru szersze pasmo jest bardziej informacyjne.</p>
<p>Jest to ta sama zależność od skali, co w pytaniach 2 i 3: <strong><code>sigma</code> jest wyborem analityka, nie właściwością danych</strong>, i podaje się ją razem z mapą.</p>
</div>
</div>
</div>
</section>
</section>
<section id="pytania-kontrolne" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="pytania-kontrolne"><span class="header-section-number">4.5</span> Pytania kontrolne</h2>
<blockquote class="blockquote">
<p><strong>1.</strong> Czym jest intensywność i dlaczego nie jest właściwością samego zbioru punktów?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Intensywność to liczba zdarzeń na jednostkę powierzchni, <span class="math inline">\(\hat{\lambda} = n/a\)</span>. Nie jest właściwością zbioru punktów, lecz <strong>pary</strong>: zbioru punktów i obszaru badań. Licznik zależy od danych, mianownik od decyzji analityka o tym, co uznać za obszar badań. Ta sama warstwa punktowa daje różne intensywności w różnych oknach analizy.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>2.</strong> Do czego służą funkcje <code>as.owin()</code> i <code>as.ppp()</code>?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Funkcje pakietu <code>spatstat</code> nie działają na obiektach klasy <code>sf</code>. <code>as.owin()</code> przekształca warstwę poligonową na <strong>okno analizy</strong> (klasa <code>owin</code>), a <code>as.ppp()</code> przekształca warstwę punktową na <strong>wzór punktowy</strong> (klasa <code>ppp</code>) zdefiniowany w tym oknie. Okno jest obowiązkowym składnikiem obiektu <code>ppp</code>, bo bez niego nie da się obliczyć intensywności.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>3.</strong> Dlaczego obiekt <code>ppp</code> przeskalowujemy funkcją <code>rescale()</code>?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Intensywność jest wyrażona w jednostkach układu współrzędnych. Dla danych w PUWG 1992 (<code>EPSG:2180</code>) jednostką jest metr, więc intensywność wychodzi w punktach na metr kwadratowy — liczba rzędu kilku milionowych, nieczytelna i trudna do porównania. <code>rescale(x, 1000)</code> przeskalowuje obiekt z metrów na kilometry, dzięki czemu intensywność jest podana w punktach na km².</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>4.</strong> Dlaczego <code>quadratcount()</code> z siatką 4×4 zwróciło 14, a nie 16 wartości?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Siatka jest zakładana na obwiednię warstwy, a następnie <strong>przycinana do okna analizy</strong>. Dwa oczka siatki 4×4 leżą w całości poza granicą Poznania, więc nie pojawiają się w wyniku.</p>
<p>Ma to bezpośrednią konsekwencję dla testu zliczania: liczba stopni swobody to liczba oczek minus jeden, czyli 13, a nie 15. Siatka utworzona funkcją <code>st_make_grid()</code> nad obwiednią ma natomiast pełne 16 oczek — w tym dwa puste — bo nie jest przycinana do żadnego okna.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>5.</strong> Czym różni się test zliczania w kwadratach od analizy gęstości jądra?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Oba badają, czy intensywność jest stała w obszarze, ale inaczej dzielą przestrzeń. Test zliczania dzieli obszar na <strong>rozłączne oczka o ustalonej wielkości</strong> i porównuje zliczenia z oczekiwanymi — daje wynik liczbowy wraz z wartością p.&nbsp;Analiza gęstości jądra używa <strong>ruchomego okna</strong> i dla każdej komórki siatki wynikowej wyznacza intensywność w jej otoczeniu — daje mapę ciągłą, bez testu.</p>
<p>Test odpowiada na pytanie „czy intensywność jest stała”, mapa gęstości na pytanie „gdzie jest wyższa, a gdzie niższa”.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>6.</strong> Co określa argument <code>sigma</code> w funkcji <code>density()</code> i jak wpływa na wynik?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>sigma</code> określa rozmiar ruchomego okna, w jednostkach układu współrzędnych — dla danych w PUWG 1992 (<code>EPSG:2180</code>) w metrach. Mniejsza wartość daje obraz bardziej szczegółowy, silniej reagujący na pojedyncze punkty; większa daje obraz wygładzony, pokazujący tendencję ogólną i tłumiący szczegóły.</p>
<p>Nie istnieje wartość „poprawna” — <code>sigma</code> jest wyborem analityka, zależnym od skali badanego zjawiska, i podaje się ją razem z mapą. Pomocną wskazówką jest typowa odległość między punktami: pasmo węższe od niej pokazuje raczej położenie poszczególnych punktów niż strukturę ich rozmieszczenia.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>7.</strong> Trzy wyniki w tym rozdziale zależą od decyzji analityka. Jakie to decyzje?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Okno analizy</strong> — decyduje o mianowniku w <span class="math inline">\(\hat{\lambda} = n/a\)</span>, a więc o średniej intensywności. Granica miasta wobec obwiedni warstwy: różnica ponad dwukrotna.</li>
<li><strong>Liczba oczek siatki</strong> — decyduje o skali, na której test zliczania szuka struktury. Siatka 4×4 i 2×2 dla szkół prowadzą do odmiennych wniosków.</li>
<li><strong>Szerokość pasma <code>sigma</code></strong> — decyduje o skali obrazu gęstości jądra.</li>
</ol>
<p>Każdą z tych trzech decyzji trzeba podać w raporcie razem z wynikiem. Wynik bez nich nie jest interpretowalny.</p>
</div>
</div>
</div>
</section>
<section id="podsumowanie" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="podsumowanie"><span class="header-section-number">4.6</span> Podsumowanie</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metoda</th>
<th>Funkcja</th>
<th>Co mówi o danych</th>
<th>Warunek poprawnego odczytu</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>średnia intensywność</td>
<td><code>summary(ppp)$intensity</code></td>
<td>ile zdarzeń wypada przeciętnie na jednostkę powierzchni</td>
<td>podawana razem z oknem analizy; zmienność w przestrzeni pokazują pozostałe metody</td>
</tr>
<tr class="even">
<td>zliczanie w siatce</td>
<td><code>quadratcount()</code></td>
<td>jak liczba zdarzeń zmienia się między oczkami</td>
<td>wynik odnosi się do zadanej liczby oczek</td>
</tr>
<tr class="odd">
<td>test zliczania w kwadratach</td>
<td><code>quadrat.test()</code></td>
<td>czy intensywność jest stała w obszarze, na skali zadanej siatką</td>
<td>wniosek dotyczy wyłącznie tej skali; wymaga <span class="math inline">\(E_i &gt; 5\)</span> w każdym oczku (sprawdzamy <code>$expected</code>), inaczej <code>method = "MonteCarlo"</code>; położenie skupień pokazuje gęstość jądra</td>
</tr>
<tr class="even">
<td>gęstość jądra</td>
<td><code>density(sigma = )</code></td>
<td>gdzie intensywność jest wyższa, a gdzie niższa</td>
<td>obraz odnosi się do przyjętego <code>sigma</code>; istotność daje <code>quadrat.test()</code></td>
</tr>
</tbody>
</table>
<p>Trzy zasady, do których wracamy w kolejnych rozdziałach:</p>
<ol type="1">
<li><strong>Okno analizy jest częścią wyniku.</strong> Intensywność bez podanego obszaru badań nie jest wynikiem analizy.</li>
<li><strong>Skala jest wyborem, nie właściwością danych.</strong> Liczba oczek siatki i szerokość pasma określają, na jakiej skali szukamy struktury — i trzeba je podać razem z wynikiem.</li>
<li><strong>Wyniki na różnych skalach nie są sprzeczne.</strong> „Losowy na skali kilku kilometrów, skupiony na skali kilkuset metrów” jest spójnym opisem jednego zjawiska.</li>
</ol>
</section>
<section id="pytanie-dla-kolejnego-rozdziału" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="pytanie-dla-kolejnego-rozdziału"><span class="header-section-number">4.7</span> Pytanie dla kolejnego rozdziału</h2>
<p>Metody z tego rozdziału opisują, <strong>ile</strong> zdarzeń wypada na jednostkę powierzchni i <strong>gdzie</strong> ta liczba jest wyższa. Robią to, dzieląc obszar na fragmenty — oczka siatki albo ruchome okno — i dlatego każdy ich wynik jest powiązany z wielkością tych fragmentów.</p>
<p>Pozostaje pytanie o <strong>odległości między punktami</strong>. Test zliczania operuje liczbą punktów w oczku, która jest taka sama, gdy leżą one stłoczone w narożniku i gdy są rozłożone równomiernie. Mapa gęstości jądra wskazuje miejsca o większym zagęszczeniu, a wzajemne odległości punktów pozostają poza zakresem obu metod.</p>
<p>Odpowiadają na nie metody oparte na odległości (<a href="08_punkty_odleglosc.html" class="quarto-xref"><span>Rozdział 5</span></a>), które podchodzą do rozkładu punktów z drugiej strony: pytają wprost o odległości między punktami i ich najbliższymi sąsiadami. Dzięki temu obywają się bez podziału obszaru na fragmenty, a więc zależą od wyboru skali inaczej niż metody z tego rozdziału.</p>
</section>
<section id="pełny-kod-analizy" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="pełny-kod-analizy"><span class="header-section-number">4.8</span> Pełny kod analizy</h2>
<p>Poniżej zebrany jest cały kod obu przykładów, w kolejności wykonania — do skopiowania do własnego skryptu zamiast przeklejania pojedynczych fragmentów. Nie ma w nim kodu objaśniającego: to dokładnie ta ścieżka, która prowadzi od danych wejściowych do wyniku. Przykład 2 korzysta z obiektów utworzonych w Przykładzie 1, więc kod uruchamia się w całości, od początku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>p2019 <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/przestepstwa_2019.gpkg"</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"granica"</span>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(p2019)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>pzn_owin <span class="ot">=</span> <span class="fu">as.owin</span>(granica)</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>p2019_ppp <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(p2019), <span class="at">W =</span> pzn_owin)</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>p2019_ppp</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>p2019_ppp_km <span class="ot">=</span> <span class="fu">rescale</span>(p2019_ppp, <span class="dv">1000</span>)</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_km)</span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_km)<span class="sc">$</span>intensity</span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>pzn_owin_bb <span class="ot">=</span> <span class="fu">as.owin</span>(<span class="fu">st_bbox</span>(granica))</span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a>p2019_ppp_bb <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(p2019), <span class="at">W =</span> pzn_owin_bb)</span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a>p2019_ppp_bb_km <span class="ot">=</span> <span class="fu">rescale</span>(p2019_ppp_bb, <span class="dv">1000</span>)</span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2019_ppp_bb_km)</span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a>obwiednia <span class="ot">=</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(granica))</span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(obwiednia) <span class="sc">+</span></span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">fill =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(granica) <span class="sc">+</span></span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a>p2019_count <span class="ot">=</span> <span class="fu">quadratcount</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-30"><a href="#cb63-30" aria-hidden="true" tabindex="-1"></a>p2019_count</span>
<span id="cb63-31"><a href="#cb63-31" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p2019_count, <span class="at">main =</span> <span class="st">"Liczba przestępstw w oczkach siatki"</span>)</span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a><span class="co"># poligon o zasięgu warstwy z granicą miasta</span></span>
<span id="cb63-33"><a href="#cb63-33" aria-hidden="true" tabindex="-1"></a>pzn_bb <span class="ot">=</span> <span class="fu">st_sf</span>(<span class="at">geom =</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(granica)))</span>
<span id="cb63-34"><a href="#cb63-34" aria-hidden="true" tabindex="-1"></a><span class="co"># siatka; argument n określa liczbę oczek w każdym kierunku</span></span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a>pzn_grid <span class="ot">=</span> <span class="fu">st_make_grid</span>(pzn_bb, <span class="at">n =</span> <span class="dv">4</span>)</span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a><span class="co"># zamiana siatki na obiekt klasy sf</span></span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf <span class="ot">=</span> <span class="fu">st_sf</span>(<span class="at">geometry =</span> pzn_grid)</span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pzn_grid_sf)</span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf<span class="sc">$</span>dane <span class="ot">=</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(pzn_grid, p2019))</span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a>pzn_grid_sf<span class="sc">$</span>dane</span>
<span id="cb63-41"><a href="#cb63-41" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(pzn_grid_sf) <span class="sc">+</span></span>
<span id="cb63-42"><a href="#cb63-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"dane"</span>,</span>
<span id="cb63-43"><a href="#cb63-43" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">n =</span> <span class="dv">4</span>, <span class="at">values =</span> <span class="st">"brewer.yl_gn"</span>),</span>
<span id="cb63-44"><a href="#cb63-44" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Liczba punktów"</span>)) <span class="sc">+</span></span>
<span id="cb63-45"><a href="#cb63-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb63-46"><a href="#cb63-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb63-47"><a href="#cb63-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-48"><a href="#cb63-48" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-49"><a href="#cb63-49" aria-hidden="true" tabindex="-1"></a>qtest <span class="ot">=</span> <span class="fu">quadrat.test</span>(p2019_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-50"><a href="#cb63-50" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(qtest, <span class="at">main =</span> <span class="st">"Test zliczania w kwadratach"</span>)</span>
<span id="cb63-51"><a href="#cb63-51" aria-hidden="true" tabindex="-1"></a>p2019_kde500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(p2019_ppp, <span class="at">sigma =</span> <span class="dv">500</span>))</span>
<span id="cb63-52"><a href="#cb63-52" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(p2019_kde500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb63-53"><a href="#cb63-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-54"><a href="#cb63-54" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(p2019_kde500) <span class="sc">+</span></span>
<span id="cb63-55"><a href="#cb63-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb63-56"><a href="#cb63-56" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Intensywność"</span>)) <span class="sc">+</span></span>
<span id="cb63-57"><a href="#cb63-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb63-58"><a href="#cb63-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb63-59"><a href="#cb63-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-60"><a href="#cb63-60" aria-hidden="true" tabindex="-1"></a>p2019_kde1500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(p2019_ppp, <span class="at">sigma =</span> <span class="dv">1500</span>))</span>
<span id="cb63-61"><a href="#cb63-61" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(p2019_kde1500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb63-62"><a href="#cb63-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-63"><a href="#cb63-63" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(p2019_kde1500) <span class="sc">+</span></span>
<span id="cb63-64"><a href="#cb63-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb63-65"><a href="#cb63-65" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Intensywność"</span>)) <span class="sc">+</span></span>
<span id="cb63-66"><a href="#cb63-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(p2019) <span class="sc">+</span></span>
<span id="cb63-67"><a href="#cb63-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>() <span class="sc">+</span></span>
<span id="cb63-68"><a href="#cb63-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-69"><a href="#cb63-69" aria-hidden="true" tabindex="-1"></a>szkoly <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/out_poznan_szkoly.gpkg"</span>, <span class="at">layer =</span> <span class="st">"szkoly"</span>)</span>
<span id="cb63-70"><a href="#cb63-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-71"><a href="#cb63-71" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(szkoly)</span>
<span id="cb63-72"><a href="#cb63-72" aria-hidden="true" tabindex="-1"></a>szkoly_ppp <span class="ot">=</span> <span class="fu">as.ppp</span>(<span class="fu">st_geometry</span>(szkoly), <span class="at">W =</span> pzn_owin)</span>
<span id="cb63-73"><a href="#cb63-73" aria-hidden="true" tabindex="-1"></a>szkoly_ppp_km <span class="ot">=</span> <span class="fu">rescale</span>(szkoly_ppp, <span class="dv">1000</span>)</span>
<span id="cb63-74"><a href="#cb63-74" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(szkoly_ppp_km)</span>
<span id="cb63-75"><a href="#cb63-75" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(szkoly_ppp_km)<span class="sc">$</span>intensity</span>
<span id="cb63-76"><a href="#cb63-76" aria-hidden="true" tabindex="-1"></a>szkoly_count <span class="ot">=</span> <span class="fu">quadratcount</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-77"><a href="#cb63-77" aria-hidden="true" tabindex="-1"></a>szkoly_count</span>
<span id="cb63-78"><a href="#cb63-78" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(szkoly_count, <span class="at">main =</span> <span class="st">"Liczba szkół w oczkach siatki"</span>)</span>
<span id="cb63-79"><a href="#cb63-79" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-80"><a href="#cb63-80" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">2</span>, <span class="at">ny =</span> <span class="dv">2</span>)</span>
<span id="cb63-81"><a href="#cb63-81" aria-hidden="true" tabindex="-1"></a><span class="fu">quadratcount</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">2</span>, <span class="at">ny =</span> <span class="dv">2</span>)</span>
<span id="cb63-82"><a href="#cb63-82" aria-hidden="true" tabindex="-1"></a>qt_sz <span class="ot">=</span> <span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>)</span>
<span id="cb63-83"><a href="#cb63-83" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sort</span>(qt_sz<span class="sc">$</span>expected), <span class="dv">2</span>)</span>
<span id="cb63-84"><a href="#cb63-84" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(qt_sz<span class="sc">$</span>expected <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb63-85"><a href="#cb63-85" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb63-86"><a href="#cb63-86" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(szkoly_ppp, <span class="at">nx =</span> <span class="dv">4</span>, <span class="at">ny =</span> <span class="dv">4</span>, <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb63-87"><a href="#cb63-87" aria-hidden="true" tabindex="-1"></a>szkoly_kde500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(szkoly_ppp, <span class="at">sigma =</span> <span class="dv">500</span>))</span>
<span id="cb63-88"><a href="#cb63-88" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(szkoly_kde500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb63-89"><a href="#cb63-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-90"><a href="#cb63-90" aria-hidden="true" tabindex="-1"></a>szkoly_kde1500 <span class="ot">=</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">density</span>(szkoly_ppp, <span class="at">sigma =</span> <span class="dv">1500</span>))</span>
<span id="cb63-91"><a href="#cb63-91" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(szkoly_kde1500) <span class="ot">=</span> <span class="fu">st_crs</span>(granica)<span class="sc">$</span>wkt</span>
<span id="cb63-92"><a href="#cb63-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-93"><a href="#cb63-93" aria-hidden="true" tabindex="-1"></a>mapa500 <span class="ot">=</span> <span class="fu">tm_shape</span>(szkoly_kde500) <span class="sc">+</span></span>
<span id="cb63-94"><a href="#cb63-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb63-95"><a href="#cb63-95" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"sigma = 500 m"</span>))</span>
<span id="cb63-96"><a href="#cb63-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-97"><a href="#cb63-97" aria-hidden="true" tabindex="-1"></a>mapa1500 <span class="ot">=</span> <span class="fu">tm_shape</span>(szkoly_kde1500) <span class="sc">+</span></span>
<span id="cb63-98"><a href="#cb63-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"-viridis"</span>),</span>
<span id="cb63-99"><a href="#cb63-99" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"sigma = 1500 m"</span>))</span>
<span id="cb63-100"><a href="#cb63-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-101"><a href="#cb63-101" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(mapa500, mapa1500)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Skopiowano!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Skopiowano!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06_punkty_centrograficzne.html" class="pagination-link" aria-label="Statystyki centrograficzne">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08_punkty_odleglosc.html" class="pagination-link" aria-label="Metody oparte na odległości">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Metody oparte na odległości</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>