<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Analiza i modelowanie struktury przestrzennej – Statystyka przestrzenna</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15_pola_estymacja.html" rel="next">
<link href="./13_pola_interpolacja.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c852b7e71cc1c09f55f367b2512aabbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Brak wyników",
    "search-matching-documents-text": "dopasowane dokumenty",
    "search-copy-link-title": "Kopiuj link do wyszukiwania",
    "search-hide-matches-text": "Ukryj dodatkowe dopasowania",
    "search-more-match-text": "więcej dopasowań w tym dokumencie",
    "search-more-matches-text": "więcej dopasowań w tym dokumencie",
    "search-clear-button-title": "Wyczyść",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Anuluj",
    "search-submit-button-title": "Zatwierdź",
    "search-label": "Szukaj"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12_pola_teoria.html">DANE POWIERZCHNIOWE CIĄGŁE PRZESTRZENNIE</a></li><li class="breadcrumb-item"><a href="./14_pola_semiwariogram.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Szukaj" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statystyka przestrzenna</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Szukaj"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O skrypcie</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_wstep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WSTĘP</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_dane_przestrzenne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Dane przestrzenne w R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_eksploracja_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EKSPLORACYJNA ANALIZA DANYCH</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_eksploracja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Eksploracyjna analiza danych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05_punkty_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE PUNKTOWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_punkty_centrograficzne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statystyki centrograficzne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_punkty_intensywnosc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metody oparte na analizie intensywności</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_punkty_odleglosc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Metody oparte na odległości</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./09_obszarowe_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE OBSZAROWE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_obszarowe_sasiedztwo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Określanie sąsiedztwa danych obszarowych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_obszarowe_autokorelacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Miary autokorelacji danych obszarowych</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./12_pola_teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DANE POWIERZCHNIOWE CIĄGŁE PRZESTRZENNIE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_pola_interpolacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Metody interpolacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_pola_semiwariogram.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_pola_estymacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Geostatystyczne metody estymacji</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_pola_ocena.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Ocena jakości estymacji</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">ZADANIA I PROJEKTY</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_zadania_samodzielne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Zadania samodzielne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_projekt1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Projekt 1: przestępczość a zmienne społeczno-ekonomiczne</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_projekt2_geostatystyka.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Projekt 2: Geostatystyka</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Załączniki</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Przełącz sekcję">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A_pakiety.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Pakiety</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B_funkcje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Funkcje</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C_operacje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Operacje na danych przestrzennych</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D_slownik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Słownik pojęć</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Spis treści</h2>
   
  <ul>
  <li><a href="#wprowadzenie" id="toc-wprowadzenie" class="nav-link active" data-scroll-target="#wprowadzenie"><span class="header-section-number">9.1</span> Wprowadzenie</a></li>
  <li><a href="#struktura-obiektów-semiwariogram-empiryczny-i-model" id="toc-struktura-obiektów-semiwariogram-empiryczny-i-model" class="nav-link" data-scroll-target="#struktura-obiektów-semiwariogram-empiryczny-i-model"><span class="header-section-number">9.2</span> Struktura obiektów: semiwariogram empiryczny i model</a></li>
  <li><a href="#semiwariogram-w-r" id="toc-semiwariogram-w-r" class="nav-link" data-scroll-target="#semiwariogram-w-r"><span class="header-section-number">9.3</span> Semiwariogram w R</a></li>
  <li><a href="#przykład-temperatura-powietrza" id="toc-przykład-temperatura-powietrza" class="nav-link" data-scroll-target="#przykład-temperatura-powietrza"><span class="header-section-number">9.4</span> Przykład: temperatura powietrza</a>
  <ul class="collapse">
  <li><a href="#krok-1-dane" id="toc-krok-1-dane" class="nav-link" data-scroll-target="#krok-1-dane">Krok 1: dane</a></li>
  <li><a href="#krok-2-wykres-rozrzutu-z-przesunięciem" id="toc-krok-2-wykres-rozrzutu-z-przesunięciem" class="nav-link" data-scroll-target="#krok-2-wykres-rozrzutu-z-przesunięciem">Krok 2: wykres rozrzutu z przesunięciem</a></li>
  <li><a href="#krok-3-obliczenia-pomocnicze" id="toc-krok-3-obliczenia-pomocnicze" class="nav-link" data-scroll-target="#krok-3-obliczenia-pomocnicze">Krok 3: obliczenia pomocnicze</a></li>
  <li><a href="#krok-4-semiwariogram-empiryczny" id="toc-krok-4-semiwariogram-empiryczny" class="nav-link" data-scroll-target="#krok-4-semiwariogram-empiryczny">Krok 4: semiwariogram empiryczny</a></li>
  <li><a href="#krok-5-modelowanie" id="toc-krok-5-modelowanie" class="nav-link" data-scroll-target="#krok-5-modelowanie">Krok 5: modelowanie</a></li>
  <li><a href="#krok-6-zapis-modelu" id="toc-krok-6-zapis-modelu" class="nav-link" data-scroll-target="#krok-6-zapis-modelu">Krok 6: zapis modelu</a></li>
  <li><a href="#interpretacja-wyniku" id="toc-interpretacja-wyniku" class="nav-link" data-scroll-target="#interpretacja-wyniku">Interpretacja wyniku</a></li>
  </ul></li>
  <li><a href="#pytania-kontrolne" id="toc-pytania-kontrolne" class="nav-link" data-scroll-target="#pytania-kontrolne"><span class="header-section-number">9.5</span> Pytania kontrolne</a></li>
  <li><a href="#podsumowanie" id="toc-podsumowanie" class="nav-link" data-scroll-target="#podsumowanie"><span class="header-section-number">9.6</span> Podsumowanie</a></li>
  <li><a href="#pełny-kod-analizy" id="toc-pełny-kod-analizy" class="nav-link" data-scroll-target="#pełny-kod-analizy"><span class="header-section-number">9.7</span> Pełny kod analizy</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12_pola_teoria.html">DANE POWIERZCHNIOWE CIĄGŁE PRZESTRZENNIE</a></li><li class="breadcrumb-item"><a href="./14_pola_semiwariogram.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-pola-semiwariogram" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analiza i modelowanie struktury przestrzennej</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Czego się nauczysz
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Po tym rozdziale potrafisz wykonać w R:</strong></p>
<ul>
<li>sporządzić wykres rozrzutu z przesunięciem (<code>hscat()</code>),</li>
<li>wykonać obliczenia pomocnicze potrzebne do doboru parametrów semiwariogramu,</li>
<li>obliczyć i wyświetlić semiwariogram empiryczny (<code>variogram()</code>),</li>
<li>zmienić maksymalny zasięg semiwariogramu i szerokość odstępów (<code>cutoff</code>, <code>width</code>),</li>
<li>zdefiniować model semiwariogramu (<code>vgm()</code>) i dopasować jego parametry (<code>fit.variogram()</code>),</li>
<li>zapisać dopasowany model do pliku.</li>
</ul>
<p><strong>Rozumiesz i umiesz zinterpretować:</strong></p>
<ul>
<li>co pokazuje wykres rozrzutu z przesunięciem i jak odczytać z niego zmienność przestrzenną,</li>
<li>trzy parametry modelu: <strong>efekt samorodka</strong>, <strong>semiwariancję progową</strong> i <strong>zasięg</strong> — oraz różnicę między semiwariancją progową a jej częścią <strong>cząstkową</strong> (<code>psill</code>),</li>
<li>dlaczego semiwariancja progowa jest tylko <strong>zbliżona</strong> do wariancji próby,</li>
<li>jak <code>cutoff</code> i <code>width</code> zmieniają kształt semiwariogramu i kiedy naruszają reguły doboru parametrów,</li>
<li>czym różnią się podstawowe modele, co oznacza <strong>zasięg praktyczny</strong> i dlaczego nie jest on tym samym co kolumna <code>range</code>,</li>
<li>jak porównać dopasowanie kilku modeli.</li>
</ul>
<p><strong>Teoria:</strong> <a href="./12_pola_teoria.html#najwazniejsze-pola">Najważniejsze informacje</a>. <strong>Funkcje:</strong> <a href="B_funkcje.html" class="quarto-xref"><span>Załącznik B</span></a>. <strong>Słownik:</strong> <a href="D_slownik.html" class="quarto-xref"><span>Załącznik D</span></a>.</p>
</div>
</div>
<section id="wprowadzenie" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="wprowadzenie"><span class="header-section-number">9.1</span> Wprowadzenie</h2>
<p>Metody deterministyczne z <a href="13_pola_interpolacja.html" class="quarto-xref"><span>Rozdział 8</span></a> szacowały wartości, nie pytając, <strong>jak zmienna zachowuje się w przestrzeni</strong>. Wykładnik potęgowy IDW ustalaliśmy arbitralnie, bo nic w danych nie wskazywało, jaka wartość jest właściwa.</p>
<p>Geostatystyka zaczyna od drugiej strony: najpierw <strong>opisuje strukturę przestrzenną</strong> zmiennej, a dopiero potem używa tego opisu do estymacji. Narzędziem opisu jest <strong>semiwariogram</strong> — wykres pokazujący, jak bardzo różnią się od siebie wartości zmierzone w punktach oddalonych o zadaną odległość. Do semiwariogramu empirycznego dopasowujemy <strong>model</strong>: funkcję ciągłą, z której można odczytać semiwariancję dla dowolnej odległości, także takiej, która w danych nie wystąpiła.</p>
<p>Ten rozdział kończy się dopasowanym modelem. Model jest <strong>wejściem</strong> do estymacji (<a href="15_pola_estymacja.html" class="quarto-xref"><span>Rozdział 10</span></a>), a ocena jakości tej estymacji należy do <a href="16_pola_ocena.html" class="quarto-xref"><span>Rozdział 11</span></a>.</p>
</section>
<section id="struktura-obiektów-semiwariogram-empiryczny-i-model" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="struktura-obiektów-semiwariogram-empiryczny-i-model"><span class="header-section-number">9.2</span> Struktura obiektów: semiwariogram empiryczny i model</h2>
<p>Funkcja <code>variogram()</code> zwraca <strong>ramkę danych</strong>, w której jeden wiersz to jeden <strong>odstęp</strong> (ang. <em>lag</em>) — przedział odległości. Kolumny: <code>np</code> — liczba par punktów w odstępie, <code>dist</code> — średnia odległość w odstępie, <code>gamma</code> — uśredniona semiwariancja par z tego odstępu.</p>
<p>Funkcja <code>vgm()</code> i <code>fit.variogram()</code> zwracają obiekt klasy <code>variogramModel</code> — również ramkę danych, ale o innym znaczeniu kolumn. Jeden wiersz to jedna <strong>składowa</strong> modelu:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Kolumna</th>
<th>Znaczenie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>model</code></td>
<td>nazwa funkcji składowej: <code>Nug</code>, <code>Sph</code>, <code>Exp</code>, <code>Gau</code>, <code>Pow</code></td>
</tr>
<tr class="even">
<td><code>psill</code></td>
<td>semiwariancja progowa <strong>cząstkowa</strong> wniesiona przez tę składową</td>
</tr>
<tr class="odd">
<td><code>range</code></td>
<td><strong>parametr zasięgu</strong> składowej — nie zawsze równy zasięgowi praktycznemu (patrz niżej); dla modelu potęgowego — wykładnik potęgowy</td>
</tr>
</tbody>
</table>
<p>Model z efektem samorodka ma <strong>dwa wiersze</strong>: <code>Nug</code> i funkcję zasadniczą. Stąd ważne rozróżnienie:</p>
<blockquote class="blockquote">
<p><strong>Semiwariancja progowa (<em>sill</em>)</strong> to maksymalny poziom zmienności w kontekście przestrzennym — suma wszystkich składowych. <strong>Semiwariancja progowa cząstkowa (<code>psill</code>)</strong> to wkład jednej składowej.</p>
<p><span class="math display">\[\text{sill} = \text{nugget} + \text{psill}\]</span></p>
</blockquote>
<p>Pomylenie tych dwóch wielkości zaniża odczytaną semiwariancję progową dokładnie o wartość efektu samorodka.</p>
</section>
<section id="semiwariogram-w-r" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="semiwariogram-w-r"><span class="header-section-number">9.3</span> Semiwariogram w R</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Czynność</th>
<th>Funkcja</th>
<th>Argumenty istotne</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>wykres rozrzutu z przesunięciem</td>
<td><code>hscat()</code></td>
<td><code>breaks</code></td>
</tr>
<tr class="even">
<td>chmura semiwariogramu</td>
<td><code>variogram(cloud = TRUE)</code></td>
<td>—</td>
</tr>
<tr class="odd">
<td>semiwariogram empiryczny</td>
<td><code>variogram()</code></td>
<td><code>cutoff</code>, <code>width</code></td>
</tr>
<tr class="even">
<td>wyświetlenie semiwariogramu</td>
<td><code>plot()</code></td>
<td><code>plot.numbers</code></td>
</tr>
<tr class="odd">
<td>definicja modelu</td>
<td><code>vgm()</code></td>
<td><code>psill</code>, <code>model</code>, <code>range</code>, <code>nugget</code></td>
</tr>
<tr class="even">
<td>dopasowanie parametrów modelu</td>
<td><code>fit.variogram()</code></td>
<td>model startowy</td>
</tr>
<tr class="odd">
<td>przegląd dostępnych modeli</td>
<td><code>show.vgms()</code></td>
<td><code>models</code>, <code>as.groups</code></td>
</tr>
</tbody>
</table>
<p>Pełne zestawienie funkcji — <a href="B_funkcje.html" class="quarto-xref"><span>Załącznik B</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="przykład-temperatura-powietrza" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="przykład-temperatura-powietrza"><span class="header-section-number">9.4</span> Przykład: temperatura powietrza</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kroki analizy
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Wczytanie danych — <code>read.csv()</code>, <code>filter()</code>, <code>st_as_sf()</code>, <code>read_sf()</code>.</li>
<li>Wykres rozrzutu z przesunięciem — <code>hscat()</code>.</li>
<li>Obliczenia pomocnicze przed doborem parametrów — <code>st_area()</code>.</li>
<li>Semiwariogram empiryczny — <code>variogram()</code>, <code>plot()</code>.</li>
<li>Modelowanie — <code>vgm()</code>, <code>fit.variogram()</code>.</li>
<li>Zapis dopasowanego modelu — <code>saveRDS()</code>.</li>
</ol>
<p>Kod spoza tych sześciu kroków jest objaśnieniem: nie trzeba go uruchamiać, żeby wykonać analizę.</p>
</div>
</div>
<section id="krok-1-dane" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-1-dane">Krok 1: dane</h3>
<p>Pracujemy na tych samych danych, co w <a href="13_pola_interpolacja.html" class="quarto-xref"><span>Rozdział 8</span></a>: pomiary temperatury powietrza (<code>data/punkty.csv</code>) i granica obszaru badań (<code>data/granica.gpkg</code>). Granica posłuży tym razem wyłącznie do obliczenia powierzchni obszaru.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>punkty <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/punkty.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(temp)) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="st">"EPSG:2180"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/granica.gpkg"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(punkty)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 247</code></pre>
</div>
</div>
</section>
<section id="krok-2-wykres-rozrzutu-z-przesunięciem" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-2-wykres-rozrzutu-z-przesunięciem">Krok 2: wykres rozrzutu z przesunięciem</h3>
<p>W klasycznej statystyce zależność między dwiema zmiennymi opisuje współczynnik korelacji. W geostatystyce badamy <strong>jedną</strong> zmienną, ale w dwóch lokalizacjach oddalonych o dystans <span class="math inline">\(h\)</span> (<strong>odstęp</strong>, ang. <em>lag</em>). Wykres rozrzutu z przesunięciem (ang. <em>h-scatterplot</em>) pokazuje tę zależność osobno dla kolejnych przedziałów odległości.</p>
<p>Argument <code>breaks</code> wyznacza granice przedziałów — poniżej co 500 m, do 4 km.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hscat</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> punkty, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4000</span>, <span class="at">by =</span> <span class="dv">500</span>))</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/hscat-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Każdy panel odpowiada jednemu przedziałowi odległości, a liczba nad nim to współczynnik korelacji par punktów z tego przedziału. Korelacja <strong>maleje wraz z odległością</strong>: pary oddalone o mniej niż 500 m mają wartości bardzo do siebie podobne, pary oddalone o ponad 3,5 km — już nie. To jest właśnie zmienność przestrzenna, którą semiwariogram opisze jedną krzywą zamiast ośmioma panelami.</p>
</section>
<section id="krok-3-obliczenia-pomocnicze" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-3-obliczenia-pomocnicze">Krok 3: obliczenia pomocnicze</h3>
<p>Przed policzeniem semiwariogramu warto znać trzy wielkości, które pomagają ocenić, czy jego parametry są sensowne: liczbę par obserwacji, średnią odległość między punktami i połowę pierwiastka z powierzchni obszaru.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># liczba wszystkich par punktów: 1/2 * n * (n - 1)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>liczba_par <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">nrow</span>(punkty) <span class="sc">*</span> (<span class="fu">nrow</span>(punkty) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># powierzchnia obszaru i średnia odległość między punktami</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>powierzchnia <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(granica))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>srednia_odleglosc <span class="ot">=</span> <span class="fu">sqrt</span>(powierzchnia <span class="sc">/</span> <span class="fu">nrow</span>(punkty))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># połowa pierwiastka z powierzchni — orientacyjny maksymalny zasięg semiwariogramu</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>polowa_pierwiastka <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">sqrt</span>(powierzchnia)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">liczba_par =</span> liczba_par,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">srednia_odleglosc =</span> srednia_odleglosc,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">polowa_pierwiastka =</span> polowa_pierwiastka)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        liczba_par  srednia_odleglosc polowa_pierwiastka 
        30381.0000           506.5428          3980.4724 </code></pre>
</div>
</div>
<p>Przy doborze parametrów semiwariogramu stosuje się kilka reguł praktycznych <span class="citation" data-cites="nowosad_geostat">(<a href="references.html#ref-nowosad_geostat" role="doc-biblioref">Nowosad, b.d.</a>)</span>:</p>
<ul>
<li>w każdym odstępie powinno się znaleźć <strong>co najmniej 30 par punktów</strong>,</li>
<li>maksymalny zasięg semiwariogramu (ang. <em>cutoff distance</em>) to <strong>połowa pierwiastka z badanej powierzchni</strong>,</li>
<li>liczba odstępów nie powinna być mniejsza niż <strong>10</strong>,</li>
<li>maksymalny zasięg semiwariogramu powinien być dłuższy o <strong>10–15%</strong> od zasięgu zjawiska.</li>
</ul>
</section>
<section id="krok-4-semiwariogram-empiryczny" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-4-semiwariogram-empiryczny">Krok 4: semiwariogram empiryczny</h3>
<p>Funkcja <code>variogram()</code> wymaga wskazania zmiennej (<code>temp ~ 1</code> — zmienna bez zmiennych objaśniających) oraz zbioru punktowego.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>vario <span class="ot">=</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> punkty)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>vario</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     np      dist     gamma dir.hor dir.ver   id
1   113  214.0615  1.205854       0       0 var1
2   296  492.6029  2.664303       0       0 var1
3   450  794.4754  4.168964       0       0 var1
4   659 1119.4215  5.258232       0       0 var1
5   825 1429.3537  6.330027       0       0 var1
6   930 1747.4842  7.078197       0       0 var1
7   960 2059.9222  7.634849       0       0 var1
8  1126 2380.7339  8.485727       0       0 var1
9  1244 2693.4708  9.900739       0       0 var1
10 1179 3012.0195  9.558005       0       0 var1
11 1294 3321.8058 11.621229       0       0 var1
12 1336 3645.0145 11.352249       0       0 var1
13 1349 3959.8583 11.863130       0       0 var1
14 1400 4277.9695 14.207606       0       0 var1
15 1458 4595.7696 15.371019       0       0 var1</code></pre>
</div>
</div>
<p>Semiwariancja <strong>rośnie wraz z odległością</strong>: od 1.21 przy średniej odległości 214 m do 15.37 przy 4596 m. Jest to ten sam fakt, który pokazał wykres rozrzutu z przesunięciem, wyrażony miarą <strong>niepodobieństwa</strong> zamiast miarą podobieństwa.</p>
<p>Argument <code>plot.numbers = TRUE</code> dopisuje do każdego punktu liczbę par, z których policzono semiwariancję.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">plot.numbers =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/wykres-semiwariogramu-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Semiwariogram empiryczny zmiennej temp wraz z liczbą par w każdym odstępie.</figcaption>
</figure>
</div>
</div>
</div>
<p>Domyślnie <code>gstat</code> przyjmuje maksymalny zasięg równy <strong>jednej trzeciej najdłuższej przekątnej</strong> obszaru, a szerokość odstępu — maksymalny zasięg podzielony przez 15. Daje to tutaj 15 odstępów sięgających 4596 m, przy czym najmniej liczny odstęp zawiera 113 par — znacznie powyżej progu 30.</p>
<p>Oba parametry można ustawić samodzielnie.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>vario_waski <span class="ot">=</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> punkty, <span class="at">cutoff =</span> <span class="dv">4000</span>, <span class="at">width =</span> <span class="dv">100</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario_waski)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/semiwariogram-cutoff-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Semiwariogram przy ręcznie ustalonym maksymalnym zasięgu i szerokości odstępu.</figcaption>
</figure>
</div>
</div>
</div>
<p>Zwróć uwagę, co zrobiło zawężenie odstępów do 100 m: odstępów jest teraz 40, ale najmniej liczny zawiera tylko 11 par — <strong>poniżej progu 30</strong>. Punkty na wykresie układają się nieregularnie, bo każdy z nich oparty jest na małej liczbie par. Reguła doboru parametrów została tu naruszona i widać to na rycinie.</p>
</section>
<section id="krok-5-modelowanie" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-5-modelowanie">Krok 5: modelowanie</h3>
<p>Do semiwariogramu empirycznego dopasowujemy <strong>model</strong> — funkcję ciągłą, z której odczytamy semiwariancję dla dowolnej odległości. Odbywa się to w dwóch etapach: najpierw podajemy model startowy z przybliżonymi parametrami, potem funkcja <code>fit.variogram()</code> dopasowuje je do danych.</p>
<p>Model startowy definiuje funkcja <code>vgm()</code>. Jej argumenty odczytujemy z wykresu semiwariogramu empirycznego:</p>
<ul>
<li><code>model</code> — kształt funkcji; tutaj sferyczny (<code>"Sph"</code>),</li>
<li><code>psill</code> — semiwariancja progowa cząstkowa: poziom, na którym krzywa się stabilizuje,</li>
<li><code>range</code> — zasięg: odległość, na której krzywa osiąga ten poziom,</li>
<li><code>nugget</code> — efekt samorodka: przesunięcie krzywej na osi <em>y</em> przy odległości bliskiej zeru.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model_startowy <span class="ot">=</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="dv">10</span>, <span class="at">model =</span> <span class="st">"Sph"</span>, <span class="at">range =</span> <span class="dv">3000</span>, <span class="at">nugget =</span> <span class="fl">0.5</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model_startowy</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  model psill range
1   Nug   0.5     0
2   Sph  10.0  3000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">model =</span> model_startowy)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/model-startowy-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Semiwariogram empiryczny z modelem startowym.</figcaption>
</figure>
</div>
</div>
</div>
<p>Model startowy ma dwa wiersze: <code>Nug</code> z wartością efektu samorodka i <code>Sph</code> z semiwariancją progową cząstkową oraz zasięgiem. Krzywa przebiega wyraźnie poniżej punktów empirycznych — parametry odczytane z wykresu były tylko przybliżeniem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">fit.variogram</span>(vario, model_startowy)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  model      psill  range
1   Nug  0.6755637    0.0
2   Sph 13.6466875 5479.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">model =</span> model)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/model-dopasowany-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Semiwariogram empiryczny z modelem po dopasowaniu parametrów.</figcaption>
</figure>
</div>
</div>
</div>
<p>Po dopasowaniu krzywa przechodzi przez punkty empiryczne.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kolumna <code>range</code> nie zawsze jest zasięgiem praktycznym
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dokumentacja <code>?vgm</code> opisuje <code>range</code> jako <strong>parametr zasięgu</strong> składowej modelu, a nie jako zasięg praktyczny. Jest to istotne, bo <code>gstat</code> zapisuje modele asymptotyczne w postaci bez mnożnika 3:</p>
<p><span class="math display">\[\gamma(h) = C\left[1 - \exp(-h/a)\right] \quad (\mathrm{Exp}), \qquad
\gamma(h) = C\left[1 - \exp(-h^{2}/a^{2})\right] \quad (\mathrm{Gau})\]</span></p>
<p>W tej postaci przy <span class="math inline">\(h = a\)</span> model osiąga nie 95%, lecz <strong>63,2%</strong> semiwariancji progowej. Zasięg praktyczny trzeba więc przeliczyć:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th><code>range</code> zwracane przez <code>fit.variogram()</code></th>
<th>Zasięg praktyczny (95% semiwariancji progowej)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Sph</code></td>
<td>zasięg <span class="math inline">\(a\)</span></td>
<td><span class="math inline">\(a\)</span> — model osiąga semiwariancję progową dokładnie na zasięgu</td>
</tr>
<tr class="even">
<td><code>Exp</code></td>
<td>parametr <span class="math inline">\(a\)</span></td>
<td><span class="math inline">\(3a\)</span></td>
</tr>
<tr class="odd">
<td><code>Gau</code></td>
<td>parametr <span class="math inline">\(a\)</span></td>
<td><span class="math inline">\(a\sqrt{3}\)</span></td>
</tr>
<tr class="even">
<td><code>Pow</code></td>
<td>wykładnik potęgowy</td>
<td>nie istnieje — model nieograniczony</td>
</tr>
</tbody>
</table>
<p>Przeliczenie sprawdzamy funkcją <code>variogramLine()</code>, która liczy wartości modelu dla zadanych odległości:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># jaki udzial semiwariancji progowej model osiaga na odleglosci rownej parametrowi range</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">"Sph"</span>, <span class="st">"Exp"</span>, <span class="st">"Gau"</span>), <span class="cf">function</span>(m)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="fu">variogramLine</span>(<span class="fu">vgm</span>(<span class="dv">1</span>, m, <span class="dv">1000</span>), <span class="at">dist_vector =</span> <span class="dv">1000</span>)<span class="sc">$</span>gamma, <span class="dv">4</span>))</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Sph    Exp    Gau 
1.0000 0.6321 0.6321 </code></pre>
</div>
</div>
<p>Model używany w tym rozdziale jest sferyczny, więc jego <code>range</code> (5480 m) <strong>jest</strong> zasięgiem. Przy modelu wykładniczym lub gaussowskim odczytanie <code>range</code> jako zasięgu zaniżyłoby go kilkukrotnie.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Objaśnienie — poza ścieżką zadania
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pakiet <code>gstat</code> udostępnia dwadzieścia modeli podstawowych; ich listę wypisuje <code>vgm()</code> wywołana bez argumentów. Cztery najczęściej używane można porównać na jednym wykresie:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.vgms</span>(<span class="at">models =</span> <span class="fu">c</span>(<span class="st">"Sph"</span>, <span class="st">"Exp"</span>, <span class="st">"Gau"</span>, <span class="st">"Pow"</span>),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">range =</span> <span class="fl">1.4</span>, <span class="at">max =</span> <span class="fl">2.5</span>, <span class="at">as.groups =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_pola_semiwariogram_files/figure-html/porownanie-modeli-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Trzy cechy odróżniają te funkcje w praktyce:</p>
<ul>
<li><strong>sferyczny</strong> (<code>Sph</code>) osiąga semiwariancję progową <strong>dokładnie</strong> na odległości równej zasięgowi i dalej pozostaje stały,</li>
<li><strong>wykładniczy</strong> (<code>Exp</code>) i <strong>gaussowski</strong> (<code>Gau</code>) zbliżają się do niej asymptotycznie, więc podaje się dla nich <strong>zasięg praktyczny</strong> — odległość, na której model osiąga 95% semiwariancji progowej; gaussowski ma przy tym charakterystyczny paraboliczny początek,</li>
<li><strong>potęgowy</strong> (<code>Pow</code>) rośnie bez ograniczenia, więc <strong>nie ma zasięgu</strong>; w jego wyniku kolumna <code>range</code> zawiera <strong>wykładnik potęgowy</strong>, nie odległość.</li>
</ul>
<p>Ostatnia różnica ma konsekwencję praktyczną: wywołanie <code>fit.variogram(vario, vgm(model = "Pow", nugget = 1))</code> <strong>przerywa działanie</strong> komunikatem <code>power model range (parameter) cannot exceed 2.0</code>, bo wartość startowa <code>range</code> jest interpretowana jako wykładnik. Dla modelu potęgowego trzeba podać <code>range</code> mniejsze od 2.</p>
</div>
</div>
</section>
<section id="krok-6-zapis-modelu" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="krok-6-zapis-modelu">Krok 6: zapis modelu</h3>
<p>Dopasowany model jest wejściem do estymacji w <a href="15_pola_estymacja.html" class="quarto-xref"><span>Rozdział 10</span></a>, więc zapisujemy go do pliku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"out"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(model, <span class="st">"out/model_semiwariogramu.rds"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpretacja-wyniku" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpretacja-wyniku">Interpretacja wyniku</h3>
<p><strong>Zmienna wykazuje wyraźną strukturę przestrzenną.</strong> Semiwariancja rośnie z odległością — wartości zmierzone blisko siebie są do siebie podobne, a podobieństwo maleje wraz z oddaleniem. Gdyby struktury nie było, semiwariogram byłby płaski.</p>
<p>Dopasowany model ma trzy parametry:</p>
<ul>
<li><strong>efekt samorodka</strong> (ang. <em>nugget</em>) = 0.6756. Jest to szacowana wariancja dla odstępu zerowego: zmienność, której semiwariogram nie wyjaśnia odległością. Składają się na nią błąd pomiarowy, zmienność w skali mniejszej niż najkrótszy odstęp między punktami oraz zmienność w obrębie samej próbki.</li>
<li><strong>semiwariancja progowa cząstkowa</strong> (<code>psill</code>) = 13.6467, a więc <strong>semiwariancja progowa</strong> = 14.3223.</li>
<li><strong>zasięg</strong> = 5480 m. Jest to odległość, na której semiwariogram osiąga semiwariancję progową — maksymalny zasięg autokorelacji danych. Pary punktów oddalone o więcej niż ta odległość nie są już do siebie podobne bardziej niż dowolne dwa punkty w obszarze.</li>
</ul>
<p><strong>Semiwariancja progowa nie jest wariancją próby.</strong> Wariancja zmiennej <code>temp</code> wynosi 15.7853, a semiwariancja progowa modelu 14.3223 — różnica 1.4631. Semiwariancja progowa jest wartością <strong>zbliżoną</strong> do wariancji próby wtedy, gdy analizowana cecha jest stacjonarna; nie jest to tożsamość.</p>
<p>Zasięg 5480 m jest większy od maksymalnego zasięgu semiwariogramu policzonego regułą połowy pierwiastka z powierzchni (3980 m) i zbliżony do zasięgu domyślnego (4596 m). Oznacza to, że struktura przestrzenna sięga niemal całego obszaru badań, a odczytana wartość zasięgu jest obarczona niepewnością — model opisuje najdalszy fragment krzywej na podstawie odstępów położonych przy samej granicy zakresu.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Objaśnienie — poza ścieżką zadania
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do tych samych danych można dopasować różne modele. Funkcja <code>fit.variogram()</code> zwraca miarę dopasowania w atrybucie <code>SSErr</code> — im mniejsza, tym krzywa bliżej punktów empirycznych.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dopasowanie <span class="ot">=</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">"Sph"</span>, <span class="st">"Exp"</span>, <span class="st">"Gau"</span>), <span class="cf">function</span>(m) {</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  f <span class="ot">=</span> <span class="fu">fit.variogram</span>(vario, <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="dv">10</span>, <span class="at">model =</span> m, <span class="at">range =</span> <span class="dv">3000</span>, <span class="at">nugget =</span> <span class="fl">0.5</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">nugget =</span> f<span class="sc">$</span>psill[<span class="dv">1</span>], <span class="at">psill =</span> f<span class="sc">$</span>psill[<span class="dv">2</span>], <span class="at">sill =</span> <span class="fu">sum</span>(f<span class="sc">$</span>psill),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">range =</span> f<span class="sc">$</span>range[<span class="dv">2</span>], <span class="at">SSErr =</span> <span class="fu">attr</span>(f, <span class="st">"SSErr"</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">t</span>(dopasowanie), <span class="dv">4</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    nugget   psill    sill    range  SSErr
Sph 0.6756 13.6467 14.3223 5479.900 0.0013
Exp 0.3434 20.2442 20.5877 4250.987 0.0008
Gau 1.3035  9.4534 10.7568 1550.690 0.0048</code></pre>
</div>
</div>
<p>Dla tych danych najlepiej dopasowuje się model <strong>wykładniczy</strong>, a nie sferyczny, którego użyliśmy w Kroku 5. Różnica w <code>SSErr</code> jest jednak niewielka, a kolumny <code>range</code> nie są wprost porównywalne między modelami: dla modelu sferycznego <code>range</code> jest zasięgiem, a dla wykładniczego i gaussowskiego — parametrem funkcji, z którego zasięg praktyczny trzeba przeliczyć (patrz ramka wyżej). Wybór modelu jest decyzją analityka opartą na kształcie krzywej w początkowym odcinku, nie wyłącznie na mierze dopasowania.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># zasieg praktyczny (95% semiwariancji progowej) przeliczony z parametru range</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>przelicz <span class="ot">=</span> <span class="fu">c</span>(<span class="at">Sph =</span> <span class="dv">1</span>, <span class="at">Exp =</span> <span class="dv">3</span>, <span class="at">Gau =</span> <span class="fu">sqrt</span>(<span class="dv">3</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(dopasowanie[<span class="st">"range"</span>, ] <span class="sc">*</span> przelicz[<span class="fu">colnames</span>(dopasowanie)])</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sph   Exp   Gau 
 5480 12753  2686 </code></pre>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="pytania-kontrolne" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="pytania-kontrolne"><span class="header-section-number">9.5</span> Pytania kontrolne</h2>
<blockquote class="blockquote">
<p><strong>1.</strong> Czym jest semiwariancja i czym różni się od korelacji?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Semiwariancja to <strong>połowa średniej kwadratu różnicy</strong> między wartościami badanej zmiennej w dwóch lokalizacjach oddalonych o wektor <span class="math inline">\(h\)</span>. Jest miarą <strong>niepodobieństwa</strong>: rośnie, gdy wartości się od siebie różnią.</p>
<p>Korelacja opisuje zależność między <strong>dwiema zmiennymi</strong>; semiwariancja opisuje zależność <strong>jednej zmiennej od samej siebie</strong>, mierzoną między dwoma punktami oddalonymi o zadany dystans. Dlatego semiwariancja rośnie tam, gdzie korelacja maleje — to dwa zapisy tego samego zjawiska.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>2.</strong> Czym różni się chmura semiwariogramu od semiwariogramu empirycznego?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Uśrednianiem.</strong> Chmura semiwariogramu (<code>variogram(cloud = TRUE)</code>) pokazuje <strong>każdą parę punktów</strong> osobno: jeden punkt wykresu to jedna para, o współrzędnych (odległość, semiwariancja). Dla 247 punktów pomiarowych jest takich par 30 381.</p>
<p>Semiwariogram empiryczny (<code>variogram()</code>) dzieli zakres odległości na <strong>odstępy</strong> i dla każdego podaje <strong>jedną</strong> uśrednioną wartość semiwariancji. Kolumna <code>np</code> mówi, z ilu par ta średnia powstała.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>3.</strong> Model semiwariogramu ma efekt samorodka 0,68 i <code>psill</code> 13,65. Ile wynosi semiwariancja progowa?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>14,33</strong> — semiwariancja progowa to <strong>suma</strong> wszystkich składowych modelu: <span class="math inline">\(\text{sill} = \text{nugget} + \text{psill}\)</span>.</p>
<p>Kolumna <code>psill</code> w wyniku <code>fit.variogram()</code> zawiera semiwariancję progową <strong>cząstkową</strong>, czyli wkład pojedynczej składowej. Odczytanie z niej semiwariancji progowej zaniża wynik dokładnie o wartość efektu samorodka.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>4.</strong> Co opisuje efekt samorodka?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Szacowaną wariancję dla odstępu <span class="math inline">\(h = 0\)</span></strong> — zmienność, której nie da się wyjaśnić odległością między punktami.</p>
<p>W teorii dwa pomiary wykonane w tym samym miejscu i czasie powinny być identyczne, a semiwariogram powinien zaczynać się w punkcie (0, 0). W praktyce tak nie jest, z trzech powodów: błędów pomiarowych, zmienności cechy w skali mniejszej niż najkrótszy odstęp między punktami pomiarowymi oraz zmienności w obrębie samej próbki.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>5.</strong> Zawęziłeś odstępy semiwariogramu argumentem <code>width</code>. Jak sprawdzisz, czy nie posunąłeś się za daleko?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sprawdzisz <strong>kolumnę <code>np</code></strong>, czyli liczbę par w każdym odstępie. Reguła praktyczna mówi, że w odstępie powinno być <strong>co najmniej 30 par</strong> <span class="citation" data-cites="nowosad_geostat">(<a href="references.html#ref-nowosad_geostat" role="doc-biblioref">Nowosad, b.d.</a>)</span>; poniżej tego progu uśredniona semiwariancja opiera się na zbyt małej liczbie obserwacji i punkty na wykresie zaczynają układać się nieregularnie.</p>
<p>W Kroku 4 zawężenie odstępów do 100 m dało 40 odstępów, ale najmniej liczny zawiera tylko 11 par — regułę naruszono i widać to na rycinie.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>6.</strong> Dlaczego dla modelu wykładniczego i gaussowskiego podaje się <strong>zasięg praktyczny</strong>?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ponieważ obie funkcje zbliżają się do semiwariancji progowej <strong>asymptotycznie</strong> — osiągają ją dopiero w nieskończoności, więc nie mają zasięgu w ścisłym znaczeniu. Zasięg praktyczny definiuje się jako odległość, na której model osiąga <strong>95%</strong> semiwariancji progowej.</p>
<p>Model sferyczny jest pod tym względem inny: osiąga semiwariancję progową dokładnie na odległości równej zasięgowi i dalej pozostaje stały.</p>
<p>Uwaga praktyczna: kolumna <code>range</code> zwracana przez <code>fit.variogram()</code> <strong>nie jest</strong> zasięgiem praktycznym dla modeli <code>Exp</code> i <code>Gau</code> — jest parametrem funkcji. Zasięg praktyczny wynosi <span class="math inline">\(3\cdot\)</span><code>range</code> dla modelu wykładniczego i <code>range</code><span class="math inline">\(\cdot\sqrt{3}\)</span> dla gaussowskiego.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>7.</strong> Dla modelu potęgowego <code>fit.variogram()</code> zwrócił <code>range</code> równe 0,93. Czy to znaczy, że zasięg autokorelacji wynosi 93 cm?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie. Model potęgowy jest modelem <strong>nieograniczonym</strong> — rośnie bez końca, więc nie ma semiwariancji progowej ani zasięgu. W jego wyniku kolumna <code>range</code> zawiera <strong>wykładnik potęgowy</strong>, czyli liczbę opisującą, jak szybko rośnie krzywa, a nie odległość.</p>
<p>Stąd też ograniczenie techniczne: wartość startowa <code>range</code> dla modelu potęgowego musi być mniejsza od 2, inaczej <code>fit.variogram()</code> przerywa działanie komunikatem <code>power model range (parameter) cannot exceed 2.0</code>.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>8.</strong> Semiwariancja progowa modelu wyniosła 14,32, a wariancja próby 15,79. Czy model jest źle dopasowany?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sprawdź odpowiedź
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nie. Semiwariancja progowa jest wartością <strong>zbliżoną</strong> do wariancji próby wtedy, gdy analizowana cecha jest <strong>stacjonarna</strong> — nie jest to tożsamość, a różnica rzędu kilku procent nie świadczy o błędzie dopasowania.</p>
<p>Jakość dopasowania ocenia się porównaniem krzywej z punktami empirycznymi, w szczególności w <strong>początkowym odcinku</strong> semiwariogramu, gdzie semiwariancja rośnie. Miarą liczbową jest <code>SSErr</code> zwracane przez <code>fit.variogram()</code>.</p>
</div>
</div>
</div>
</section>
<section id="podsumowanie" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="podsumowanie"><span class="header-section-number">9.6</span> Podsumowanie</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pojęcie / metoda</th>
<th>Funkcja</th>
<th>Co mówi o danych</th>
<th>Warunek poprawnego odczytu</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>wykres rozrzutu z przesunięciem</td>
<td><code>hscat(breaks = )</code></td>
<td>jak maleje podobieństwo wartości wraz z odległością</td>
<td>jeden panel na przedział odległości</td>
</tr>
<tr class="even">
<td>chmura semiwariogramu</td>
<td><code>variogram(cloud = TRUE)</code></td>
<td>semiwariancja każdej pary punktów osobno</td>
<td>bez uśredniania; służy wykrywaniu par odstających</td>
</tr>
<tr class="odd">
<td>semiwariogram empiryczny</td>
<td><code>variogram(cutoff = , width = )</code></td>
<td>uśredniona semiwariancja dla kolejnych odstępów</td>
<td>min. 30 par w odstępie, min. 10 odstępów <span class="citation" data-cites="nowosad_geostat">(<a href="references.html#ref-nowosad_geostat" role="doc-biblioref">Nowosad, b.d.</a>)</span></td>
</tr>
<tr class="even">
<td>efekt samorodka</td>
<td><code>model$psill[1]</code></td>
<td>zmienność niewyjaśniona odległością: błąd pomiaru, skala poniżej najkrótszego odstępu, zmienność w próbce</td>
<td>odczytywany jako przesunięcie krzywej na osi <em>y</em></td>
</tr>
<tr class="odd">
<td>semiwariancja progowa</td>
<td><code>sum(model$psill)</code></td>
<td>maksymalny poziom zmienności przestrzennej</td>
<td><strong>suma</strong> składowych; <code>psill</code> to tylko część cząstkowa</td>
</tr>
<tr class="even">
<td>zasięg</td>
<td><code>model$range[2]</code></td>
<td>parametr zasięgu składowej modelu</td>
<td>dla <code>Sph</code> równy zasięgowi; dla <code>Exp</code> zasięg praktyczny to <span class="math inline">\(3\cdot\)</span><code>range</code>, dla <code>Gau</code> — <code>range</code><span class="math inline">\(\cdot\sqrt{3}\)</span>; dla <code>Pow</code> kolumna zawiera wykładnik</td>
</tr>
<tr class="odd">
<td>model semiwariogramu</td>
<td><code>vgm()</code> + <code>fit.variogram()</code></td>
<td>ciągły opis struktury przestrzennej, wejście do estymacji</td>
<td>oceniany po dopasowaniu w początkowym odcinku krzywej</td>
</tr>
</tbody>
</table>
<p>Trzy zasady, do których wracamy w kolejnych rozdziałach:</p>
<ol type="1">
<li><strong>Semiwariancja progowa to suma składowych modelu.</strong> <code>psill</code> w wyniku <code>fit.variogram()</code> jest wartością cząstkową; semiwariancja progowa to <code>nugget + psill</code>.</li>
<li><strong>Parametry semiwariogramu podajemy razem z wynikiem.</strong> <code>cutoff</code> i <code>width</code> zmieniają kształt krzywej, a tym samym odczytane parametry modelu. Liczbę par w odstępie sprawdzamy w kolumnie <code>np</code>.</li>
<li><strong>Model semiwariogramu jest decyzją analityka.</strong> Miara dopasowania <code>SSErr</code> jest jedną z przesłanek, a nie rozstrzygnięciem — kształt krzywej w początkowym odcinku jest ważniejszy niż dopasowanie na końcu zakresu.</li>
</ol>
</section>
<section id="pełny-kod-analizy" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="pełny-kod-analizy"><span class="header-section-number">9.7</span> Pełny kod analizy</h2>
<p>Poniżej zebrany jest cały kod Kroków 1–6 w kolejności wykonania — do skopiowania do własnego skryptu zamiast przeklejania pojedynczych fragmentów. Nie ma w nim kodu objaśniającego: to dokładnie ta ścieżka, która prowadzi od danych wejściowych do zapisanego modelu <code>out/model_semiwariogramu.rds</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>punkty <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/punkty.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(temp)) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="st">"EPSG:2180"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>granica <span class="ot">=</span> <span class="fu">read_sf</span>(<span class="st">"data/granica.gpkg"</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(punkty)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hscat</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> punkty, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4000</span>, <span class="at">by =</span> <span class="dv">500</span>))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># liczba wszystkich par punktów: 1/2 * n * (n - 1)</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>liczba_par <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">nrow</span>(punkty) <span class="sc">*</span> (<span class="fu">nrow</span>(punkty) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># powierzchnia obszaru i średnia odległość między punktami</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>powierzchnia <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(granica))</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>srednia_odleglosc <span class="ot">=</span> <span class="fu">sqrt</span>(powierzchnia <span class="sc">/</span> <span class="fu">nrow</span>(punkty))</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># połowa pierwiastka z powierzchni — orientacyjny maksymalny zasięg semiwariogramu</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>polowa_pierwiastka <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">sqrt</span>(powierzchnia)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">liczba_par =</span> liczba_par,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">srednia_odleglosc =</span> srednia_odleglosc,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">polowa_pierwiastka =</span> polowa_pierwiastka)</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>vario <span class="ot">=</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> punkty)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>vario</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">plot.numbers =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>vario_waski <span class="ot">=</span> <span class="fu">variogram</span>(temp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> punkty, <span class="at">cutoff =</span> <span class="dv">4000</span>, <span class="at">width =</span> <span class="dv">100</span>)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario_waski)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>model_startowy <span class="ot">=</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="dv">10</span>, <span class="at">model =</span> <span class="st">"Sph"</span>, <span class="at">range =</span> <span class="dv">3000</span>, <span class="at">nugget =</span> <span class="fl">0.5</span>)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>model_startowy</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">model =</span> model_startowy)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">fit.variogram</span>(vario, model_startowy)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>model</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vario, <span class="at">model =</span> model)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"out"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(model, <span class="st">"out/model_semiwariogramu.rds"</span>)</span></code><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-nowosad_geostat" class="csl-entry" role="listitem">
Nowosad, Jakub. b.d. <em>Geostatystyka w R</em>. <a href="https://jakubnowosad.com/geostat_book/">https://jakubnowosad.com/geostat_book/</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Skopiowano!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Skopiowano!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13_pola_interpolacja.html" class="pagination-link" aria-label="Metody interpolacji">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Metody interpolacji</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15_pola_estymacja.html" class="pagination-link" aria-label="Geostatystyczne metody estymacji">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Geostatystyczne metody estymacji</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>