project:
  type: book

book:
  title: "Statystyka przestrzenna"
  author: "Jakub Nowosad, Anna Dmowska"
  date: 2025-09-19
  date-format: iso
  chapters:
    - index.qmd
    - part: 01_wstep.qmd
      chapters:
        - 02_dane_przestrzenne.qmd
    - part: 03_eksploracja_teoria.qmd
      chapters:
        - 04_eksploracja.qmd
    - part: 05_punkty_teoria.qmd
      chapters:
        - 06_punkty_centrograficzne.qmd
        - 07_punkty_intensywnosc.qmd
        - 08_punkty_odleglosc.qmd
    - part: 09_obszarowe_teoria.qmd
      chapters:
        - 10_obszarowe_sasiedztwo.qmd
        - 11_obszarowe_autokorelacja.qmd
    - part: 12_pola_teoria.qmd
      chapters:
        - 13_pola_interpolacja.qmd
        - 14_pola_semiwariogram.qmd
        - 15_pola_estymacja.qmd
        - 16_pola_ocena.qmd
    - part: "ZADANIA I PROJEKTY"
      chapters:
        - 17_zadania_samodzielne.qmd
        - 18_projekt1.qmd
        - 19_projekt2_geostatystyka.qmd
  appendices:
    - A_pakiety.qmd
    - B_funkcje.qmd
    - C_operacje.qmd
    - D_slownik.qmd
    - references.qmd

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

lang: pl

editor: visual
